"use client";
import { useState } from 'react';
import { FINANCE_TABS, csvCell, date, label, money, text, type PortalRow } from '../lib/adminPortalModel.ts';
import { AdminCosts } from './AdminCosts';
import { AdminPortalDocuments } from './AdminPortalDocuments';
import { BusinessContext, BusinessTable, Chip, Info, MoneySummary, Period, ReadState, RecordDetails, Tabs, portalRequest, usePortalRead } from './AdminPortalShared';

export function AdminPortalFinance({tab,onTab,onSessionLost,onCreator,initialFilter=""}:{tab:string;onTab:(tab:string)=>void;onSessionLost:()=>void;onCreator?:()=>void;initialFilter?:string}){
  const [period,setPeriod]=useState<PortalRow>({period:'month'});
  return <><Tabs items={FINANCE_TABS} value={tab} onChange={onTab}/>{tab==='AUSGABEN'?<AdminCosts onSessionLost={onSessionLost} expensesOnly initialFilter={initialFilter}/>:tab==='DOKUMENTE'?<AdminPortalDocuments/>:<><Period value={period} onChange={setPeriod}/>{tab==='EINNAHMEN'?<Ledger key={JSON.stringify(period)} period={period}/>:<FinanceSummary period={period} reports={tab==='AUSWERTUNGEN'} onCreator={onCreator}/>}</>}</>;
}
export function FinanceSummary({period,reports=false,onCreator}:{period:PortalRow;reports?:boolean;onCreator?:()=>void}){
  const {data,error,refresh}=usePortalRead('/api/admin/finance',{action:'summary',...period});
  const [exportError,setExportError]=useState('');const [exporting,setExporting]=useState(false);
  const summary=data?.summary as PortalRow|null;
  async function exportLedger(){
    setExporting(true);setExportError('');
    try{
      const result=await portalRequest('/api/admin/finance',{action:'export',...period});
      const headers=['Datum','Art','Kanal','Brutto in Cent','Netto in Cent','Steuer in Cent','Referenz','Basis'];
      const rows=(result.events as PortalRow[]).map(row=>[row.occurred_on,label(row.kind),label(row.channel),row.gross_cents,row.net_cents,row.tax_cents,row.external_reference,row.occurred_on_basis]);
      const expenses=(result.expenses as PortalRow[]).map(row=>[row.occurred_on,`Ausgabe: ${label(row.category)}`,label(row.channel),row.gross_cents,null,row.vat_cents,row.order_id,row.description]);
      const csv='\uFEFF'+[headers,...rows,...expenses].map(row=>row.map(csvCell).join(';')).join('\r\n');
      const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='gloa-finanzereignisse.csv';a.click();URL.revokeObjectURL(url);
    }catch(error){setExportError(error instanceof Error?error.message:'Export fehlgeschlagen.');}finally{setExporting(false);}
  }
  return <><div className="portal-section-head"><h2>{reports?'Auswertungen':'Finanzübersicht'}</h2><button type="button" onClick={refresh}>Aktualisieren</button></div><ReadState data={data} error={error} retry={refresh}><MoneySummary summary={summary}/>{data?.undatedEvents===null?<p className="portal-warning">Ereignisse ohne Datum konnten nicht geprüft werden.</p>:Number(data?.undatedEvents)>0?<p className="portal-warning">{String(data?.undatedEvents)} Finanzereignisse ohne gesichertes Datum sind keinem Zeitraum zugeordnet. In Einnahmen unter „Ohne bekanntes Datum“ prüfen.</p>:null}<p className="portal-note">Aktuell offene Provisionsbuchungen: {typeof data?.creatorObligations==='number'?data.creatorObligations:'unbekannt'}. {onCreator&&<button type="button" onClick={onCreator}>Provisionsstände und Zusammensetzung prüfen</button>} Diese Verpflichtungen sind kein bereits gezahlter Aufwand im gewählten Zeitraum.</p><h3>Einnahmen und Refunds nach Kanal</h3><BusinessTable rows={(summary?.channels??[]) as PortalRow[]} columns={[{key:'channel',title:'Kanal',render:r=>label(r.channel)},{key:'incomeCents',title:'Einnahmen',render:r=>money(r.incomeCents)},{key:'refundCents',title:'Refunds',render:r=>money(r.refundCents)},{key:'knownCostCents',title:'Erfasste Kosten',render:r=>money(r.knownCostCents)}]}/><h3>Gespeicherte Steuerwerte <Info>Dies ist keine Steuerberechnung und keine Steuererklärung. Fehlende gespeicherte Werte bleiben unbekannt.</Info></h3><dl className="portal-metrics"><div><dt>USt auf Einnahmen</dt><dd>{money(summary?.storedIncomeTaxCents)}</dd></div><div><dt>USt auf Refunds</dt><dd>{money(summary?.storedRefundTaxCents)}</dd></div><div><dt>Erfasste Vorsteuer</dt><dd>{money(summary?.storedInputTaxCents)}</dd></div></dl>{reports&&<><button type="button" disabled={exporting} onClick={()=>void exportLedger()}>{exporting?'Export wird erstellt …':'CSV für Excel exportieren'}</button><p className="portal-note">Alle Ledger-Ereignisse und erfassten Ausgaben im gewählten Zeitraum. Leere Felder bedeuten nicht erfasst. Beträge werden unverändert in Cent exportiert.</p>{exportError&&<p role="alert" className="portal-error">{exportError}</p>}</>}</ReadState></>;
}
function Ledger({period}:{period:PortalRow}){
  const [undated,setUndated]=useState(false);
  const [page,setPage]=useState(1),[kind,setKind]=useState('all'),[channel,setChannel]=useState('all');const [selected,setSelected]=useState<PortalRow|null>(null);
  const {data,error,refresh}=usePortalRead('/api/admin/finance',{action:'list',...period,page,kind,channel,undated});
  const rows=(data?.events??[]) as PortalRow[];
  const entity=selected?.order_id?'order':selected?.annual_plan_id?'annual_plan':selected?.subscription_id?'subscription':selected?.b2b_agreement_id?'b2b_agreement':null;
  const id=selected?.order_id??selected?.annual_plan_id??selected?.subscription_id??selected?.b2b_agreement_id;
  return <><div className="portal-controls"><label>Datum<select value={undated?'undated':'period'} onChange={e=>{setUndated(e.target.value==='undated');setPage(1);}}><option value="period">Gewählter Zeitraum</option><option value="undated">Ohne bekanntes Datum</option></select></label><label>Art<select value={kind} onChange={e=>{setKind(e.target.value);setPage(1);}}><option value="all">Alle Ereignisse</option>{['order_payment','annual_prepayment','b2b_settlement','refund','payment_fee'].map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label><label>Kanal<select value={channel} onChange={e=>{setChannel(e.target.value);setPage(1);}}><option value="all">Alle Kanäle</option>{['b2c','b2b','event','internal'].map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label><button type="button" onClick={refresh}>Aktualisieren</button></div><ReadState data={data} error={error} retry={refresh}><BusinessTable rows={rows} onOpen={setSelected} columns={[{key:'occurred_on',title:'Datum',render:r=>date(r.occurred_on)},{key:'kind',title:'Art',render:r=><Chip value={r.kind}/>},{key:'reference',title:'Geschäftsbezug',render:r=>text((r.orders as PortalRow)?.order_number,r.annual_plan_id?'Jahresvorauszahlung':r.b2b_agreement_id?'B2B-Zahlungsplan':text(r.external_reference))},{key:'channel',title:'Kanal',render:r=>label(r.channel)},{key:'gross_cents',title:'Betrag',render:r=>money(r.gross_cents)},{key:'direction',title:'Kontext',render:r=>r.direction==='inflow'?'Eingang':'Ausgang'},{key:'occurred_on_basis',title:'Datum laut',render:r=>label(r.occurred_on_basis)}]}/><div className="portal-pagination"><button type="button" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Zurück</button><span>Seite {page} · {typeof data?.total==='number'?data.total:'unbekannt'} Ereignisse</span><button type="button" disabled={typeof data?.total!=='number'||page*Number(data.pageSize)>=data.total} onClick={()=>setPage(p=>p+1)}>Weiter</button></div></ReadState><RecordDetails row={selected} title={label(selected?.kind)} onClose={()=>setSelected(null)}>{selected&&<><dl className="portal-facts"><div><dt>Datum</dt><dd>{date(selected.occurred_on)}</dd></div><div><dt>Betrag</dt><dd>{money(selected.gross_cents)}</dd></div><div><dt>Notiz</dt><dd>{text(selected.note)}</dd></div></dl>{entity&&typeof id==='string'&&<BusinessContext entity={entity} id={id}/>}</>}</RecordDetails></>;
}
