"use client";
import {useState,type ReactNode} from 'react';
import {PRIMARY_AREAS,text,type PortalArea,type PortalRow} from '../lib/adminPortalModel.ts';
import {Chip,portalRequest} from './AdminPortalShared';
import {canWrite,parseAdminRole} from '../lib/adminRoles';

export function AdminPortalShell({area,identity,navigate,signOut,children}:{area:PortalArea;identity:PortalRow;navigate:(area:PortalArea,tab?:string,filter?:string)=>void;signOut:()=>void;children:ReactNode}){
 const [search,setSearch]=useState(''),[results,setResults]=useState<PortalRow[]|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function find(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');setResults(null);try{const data=await portalRequest('/api/admin/portal',{action:'search',search});setResults(data.results as PortalRow[]);}catch(e){setError(e instanceof Error?e.message:'Suche fehlgeschlagen.');}finally{setBusy(false);}}
 const descriptions:Record<PortalArea,string>={overview:'Was heute wichtig ist.',sales:'Bestellungen, Abos und Jahrespläne an einem Ort.',rights:'Fälle prüfen und Entscheidungen nachvollziehbar treffen.',finance:'Geldeingänge, Ausgaben und Belege aus den gespeicherten Geschäftsvorgängen.',inventory:'Bestände und manuelle Bewegungen.',creator:'Beziehungen, Affiliate, Content und Provisionen.',b2b:'Vereinbarungen, Zahlungen und Lieferungen.',activity:'Was passiert ist und wer gehandelt hat.'};
 const sensitive=canWrite(parseAdminRole(identity.role));
 return <><aside className="portal-sidebar"><button type="button" className="portal-brand" onClick={()=>navigate("overview")}>GLOA<span>OPERATIONS</span></button><nav aria-label="Hauptnavigation">{PRIMARY_AREAS.filter(([key])=>sensitive||!['finance','rights','b2b'].includes(key)).map(([key,name])=><button key={key} type="button" aria-current={key===area?'page':undefined} className={key===area?'is-active':''} onClick={()=>navigate(key)}>{name}</button>)}</nav><div className="portal-operator"><strong>{text(identity.displayName??identity.display_name,identity.email as string)}</strong><span>{text(identity.email)}</span><Chip value={identity.role}/><button type="button" onClick={signOut}>Abmelden</button></div></aside><div className="portal-workspace"><header className="portal-header"><div><p className="portal-eyebrow">GLOA OPERATIONS</p><h1>{PRIMARY_AREAS.find(([key])=>key===area)?.[1]}</h1><p>{descriptions[area]}</p></div><form role="search" onSubmit={find}><label htmlFor="portal-search">Globale Suche</label><div><input id="portal-search" type="search" value={search} minLength={2} placeholder="Bestellung, Kunde, Creator …" onChange={e=>setSearch(e.target.value)}/><button type="submit" disabled={busy||search.trim().length<2}>{busy?'Suche …':'Suchen'}</button></div></form></header>{error&&<p role="alert" className="portal-error">{error}<button type="button" onClick={()=>setError('')}>Schließen</button></p>}{results&&<section className="portal-search-results" aria-label="Suchergebnisse"><div className="portal-section-head"><h2>Suchergebnisse</h2><button type="button" onClick={()=>setResults(null)}>Schließen</button></div>{!results.length?<p>Keine passenden Geschäftsobjekte.</p>:results.map((r,i)=><button type="button" key={`${r.entity}-${r.id}-${i}`} onClick={()=>{navigate(r.area as PortalArea,text(r.tab,''),String(r.order_number??r.id));setResults(null);}}><strong>{text(r.order_number??r.display_name??r.code??r.customer_name??(r.customer_snapshot as PortalRow)?.name??(r.business_snapshot as PortalRow)?.companyName??(r.business_snapshot as PortalRow)?.company_name,'Geschäftsobjekt')}</strong><span>{text(r.email??r.contact_email??(r.customer_snapshot as PortalRow)?.email)}</span><Chip value={r.status??r.case_state}/></button>)}<p className="portal-note">Bis zu 12 Treffer je Geschäftsbereich.</p></section>}<div className="portal-content">{children}</div></div></>;
}
