"use client";
import {useState} from 'react';
import {label,text,type PortalRow} from '../lib/adminPortalModel.ts';
import {portalRequest} from './AdminPortalShared';

export function AdminPortalDocumentAssociation({busy}:{busy:boolean}){
  const [kind,setKind]=useState('order'),[query,setQuery]=useState(''),[results,setResults]=useState<PortalRow[]>([]),[selected,setSelected]=useState(''),[error,setError]=useState(''),[searching,setSearching]=useState(false);
  async function search(){setSearching(true);setError('');setResults([]);try{const result=await portalRequest('/api/admin/portal',{action:'search',search:query});const table=({order:'orders',annual_plan:'annual_plans',b2b_agreement:'b2b_supply_agreements',creator:'creators',business_expense:'business_expenses'} as Record<string,string>)[kind];setResults((result.results as PortalRow[]).filter(r=>r.entity===table));}catch(e){setError(e instanceof Error?e.message:'Suche fehlgeschlagen.');}finally{setSearching(false);}}
  return <><label>Bereich<select name="entityType" value={kind} onChange={e=>{setKind(e.target.value);setSelected('');setResults([]);}}>{['order','business_expense','annual_plan','b2b_agreement','customer','creator'].map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label>{kind!=='customer'&&<><label>Geschäftsobjekt suchen<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Bestellnummer, Name oder E-Mail"/></label><button type="button" disabled={busy||searching||query.trim().length<2} onClick={()=>void search()}>{searching?'Suche …':'Suchen'}</button><label>Geschäftsobjekt<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Bitte wählen</option>{results.map(r=><option key={String(r.id)} value={String(r.id)}>{text(r.order_number??r.display_name??r.description??(r.business_snapshot as PortalRow)?.companyName??(r.customer_snapshot as PortalRow)?.name,'Geschäftsobjekt')} · {text(r.email??(r.customer_snapshot as PortalRow)?.email,'')}</option>)}</select></label></>}{error&&<p role="alert">{error}</p>}<input type="hidden" name="entityId" value={selected}/><details><summary>Weitere Details: vorhandene Datensatz-ID</summary><label>Datensatz-ID<input value={selected} pattern="[0-9a-fA-F-]{36}" onChange={e=>setSelected(e.target.value)}/></label><p className="portal-note">Kundenbezüge verwenden die vorhandene Nutzer-ID. Es wird kein Kunde angelegt.</p></details><button disabled={busy||!selected} type="submit">Zuordnung speichern</button></>;
}
