"use client";
import { useState } from "react";
import { BRAND } from "./content";
import { track } from "./analytics";

const links = [["/shop","Shop"],["/our-matcha","Our Matcha"],["/about","About"],["/for-cafes","For Cafés"],["/journal","Journal"]];
export function Mark(){return <a className="wordmark" href="/" aria-label="GLOA Startseite">GLOA<span>®</span></a>}
export function Header({onCart}:{onCart:()=>void}){
 const [open,setOpen]=useState(false); const [search,setSearch]=useState(false);
 return <><div className="ticker"><span>GLOA · MATCHA AUS SHIZUOKA</span><span>BALD DA</span><span>FOR CAFÉS →</span></div><header><Mark/><nav aria-label="Hauptnavigation">{links.map(([h,l])=><a className={h==="/for-cafes"?"business-link":""} key={h} href={h}>{l}</a>)}</nav><div className="head-actions"><button onClick={()=>setSearch(!search)} aria-expanded={search}>Search</button><button onClick={onCart}>Bag <b>0</b></button><button className="menu" onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls="mobile-menu">{open?"Close":"Menu"}</button></div></header>{search&&<form className="search-bar" role="search" onSubmit={e=>e.preventDefault()}><label htmlFor="site-search">Search GLOA</label><input autoFocus id="site-search" placeholder="Matcha, recipes, cafés…"/><button>Search</button></form>}{open&&<nav id="mobile-menu" className="mobile-nav" aria-label="Mobile Navigation">{links.map(([h,l],i)=><a key={h} href={h}><span>0{i+1}</span>{l}</a>)}</nav>}</>
}
export function Newsletter(){const [done,setDone]=useState(false);return <section className="newsletter-band"><p className="eyebrow">STAY IN THE GLOA.</p><h2>Wir sagen<br/><i>dir Bescheid.</i></h2>{done?<p className="success-line">Drin. Willkommen bei GLOA.</p>:<form onSubmit={e=>{e.preventDefault();track("newsletter_signup");setDone(true)}}><label className="sr-only" htmlFor="newsletter">E-Mail-Adresse</label><input required type="email" id="newsletter" placeholder="E-Mail-Adresse"/><button>Join ↗</button><label className="consent"><input required type="checkbox"/> Ich möchte den GLOA Newsletter erhalten und akzeptiere die Datenschutzhinweise.</label></form>}<p>Rezepte, Drops, Café-Entdeckungen und alles rund um GLOA.</p></section>}
export function Footer(){return <footer><div><Mark/><p>Matcha aus Japan.<br/>Gemacht in Berlin.</p></div><div><p className="eyebrow">SHOP</p><a href="/shop">Shop</a><a href="/our-matcha">Our Matcha</a></div><div><p className="eyebrow">GLOA</p><a href="/about">About</a><a href="/journal">Journal</a><a href="/contact">Contact</a></div><div><p className="eyebrow">BUSINESS</p><a href="/for-cafes">For Cafés</a><a href="/for-cafes#lead">Wholesale Inquiry</a><a href="/for-cafes?intent=sample#lead">Request a Sample</a></div><div><p className="eyebrow">LEGAL</p>{[["impressum","Impressum"],["datenschutz","Datenschutz"],["agb","AGB"],["widerruf","Widerruf"],["versand","Versand"]].map(([h,l])=><a key={h} href={`/${h}`}>{l}</a>)}</div><div className="social-note"><p className="eyebrow">SOCIAL</p><a href={`https://instagram.com/${BRAND.instagram}`} target="_blank" rel="noopener noreferrer">Instagram</a></div><div className="legal"><span>© 2026 GLOA</span><span>GLOA · BERLIN</span></div></footer>}
