"use client";
import { useState, useEffect } from "react";
import { BRAND } from "./content";
import { track } from "./analytics";

const links:[ string, string ][] = [["/shop","Kaufen"],["/our-matcha","Unser Matcha"],["/about","Über GLOA"],["/for-cafes","B2B"],["/journal","Journal"]];
export function Mark(){return <a className="wordmark" href="/" aria-label="GLOA Startseite">GLOA<span>®</span></a>}
export function Header({onCart}:{onCart:()=>void}){
 const [open,setOpen]=useState(false);const [search,setSearch]=useState(false);const [scrolled,setScrolled]=useState(false);const [path,setPath]=useState("");
 useEffect(()=>{setPath(window.location.pathname);const s=()=>setScrolled(window.scrollY>10);window.addEventListener("scroll",s,{passive:true});return()=>window.removeEventListener("scroll",s)},[]);
 useEffect(()=>{document.body.style.overflow=open?"hidden":"";return()=>{document.body.style.overflow=""}},[open]);
 return <><div className="brand-bar"><span className="bb-left">GLOA · SHIZUOKA, JAPAN</span><span className="bb-center">MATCHA FOR REAL LIFE.</span><span className="bb-right"><a href="/for-cafes">B2B →</a></span><span className="bb-mobile">MATCHA FROM SHIZUOKA · BERLIN</span></div><header className={scrolled?"compact":""}><button className="menu" onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls="mobile-menu">{open?"Close":"Menu"}</button><Mark/><nav aria-label="Hauptnavigation">{links.map(([h,l])=><a key={h} href={h} className={path===h?"nav-active":""}>{l}</a>)}</nav><div className="head-actions"><button onClick={()=>setSearch(!search)} aria-expanded={search}>Search</button><button className="bag-btn" onClick={onCart}>Bag <span className="bag-count">0</span></button></div>{search&&<form className="search-bar" role="search" onSubmit={e=>e.preventDefault()}><label htmlFor="site-search">Search GLOA</label><input autoFocus id="site-search" placeholder="Matcha, Rezepte, Cafés…"/><button>Search</button></form>}</header>{open&&<nav id="mobile-menu" className="mobile-nav" aria-label="Mobile Navigation">{links.map(([h,l])=><a key={h} href={h} onClick={()=>setOpen(false)}>{l}</a>)}</nav>}</>
}
export function Newsletter(){const [done,setDone]=useState(false);return <section className="newsletter-band"><div className="newsletter-copy"><p className="eyebrow">STAY IN THE GLOA.</p><h2>Wir sagen<br/><i>dir Bescheid.</i></h2><p>Rezepte, Drops, Café-Entdeckungen und alles rund um GLOA.</p></div>{done?<p className="success-line">Drin. Willkommen bei GLOA.</p>:<form onSubmit={e=>{e.preventDefault();track("newsletter_signup");setDone(true)}}><label className="sr-only" htmlFor="newsletter">E-Mail-Adresse</label><input required type="email" id="newsletter" placeholder="E-Mail-Adresse"/><button>Join</button><label className="consent"><input required type="checkbox"/> Ich möchte den GLOA Newsletter erhalten und akzeptiere die Datenschutzhinweise.</label></form>}<div className="newsletter-img"><img src="/img/gloa-newsletter.png" alt="Iced Matcha Lifestyle" loading="lazy"/></div></section>}
export function Footer(){return <footer><div><Mark/><p>Matcha aus Japan.<br/>Gemacht in Berlin.</p></div><div><p className="eyebrow">KAUFEN</p><a href="/shop">Matcha</a><a href="/our-matcha">Unser Matcha</a></div><div><p className="eyebrow">GLOA</p><a href="/about">Über GLOA</a><a href="/journal">Journal</a><a href="/contact">Kontakt</a></div><div><p className="eyebrow">BUSINESS</p><a href="/for-cafes">B2B</a><a href="/for-cafes#lead">B2B-Anfrage</a><a href="/for-cafes?intent=sample#lead">Sample anfragen</a></div><div><p className="eyebrow">LEGAL</p>{[["impressum","Impressum"],["datenschutz","Datenschutz"],["agb","AGB"],["widerruf","Widerruf"],["versand","Versand"]].map(([h,l])=><a key={h} href={`/${h}`}>{l}</a>)}</div><div className="social-note"><p className="eyebrow">SOCIAL</p><a href="https://www.tiktok.com/@gloa.matcha" target="_blank" rel="noopener noreferrer">TikTok</a><a href={`https://instagram.com/${BRAND.instagram}`} target="_blank" rel="noopener noreferrer">Instagram</a></div><div className="legal"><span>© 2026 GLOA</span><span>GLOA · BERLIN</span></div></footer>}
