"use client";
import { useEffect, useState, useRef } from "react";
import { Header, Footer, Newsletter } from "./Chrome";
import { BRAND, BUSINESS_FACTS, PRODUCT } from "./content";
import { BusinessCalculator } from "./BusinessCalculator";
import { track } from "./analytics";

const articles=[{slug:"classic-matcha-latte",type:"RECIPE",title:"Classic Matcha Latte",time:"5 MIN",tone:"j0",image:"/img/gloa-morning.png",alt:"Classic Matcha Latte"},{slug:"iced-matcha-latte",type:"RECIPE",title:"Iced Matcha Latte",time:"4 MIN",tone:"j2",image:"/img/gloa-iced.png",alt:"Iced Matcha Latte"},{slug:"strawberry-matcha",type:"RECIPE",title:"Strawberry Matcha",time:"6 MIN",tone:"j3",image:"/img/gloa-strawberry-matcha.png",alt:"Strawberry Matcha Latte"},{slug:"matcha-in-the-city",type:"CULTURE",title:"Matcha in the city",time:"READ",tone:"j1",image:"/img/gloa-matcha-in-the-city.png",alt:"Matcha unterwegs in Berlin"}];
const dailyTiles=[{label:"MORNING",src:"/img/gloa-morning.png",alt:"Matcha am Morgen"},{label:"WORK",src:"/img/gloa-work.png",alt:"Iced Matcha am Arbeitsplatz"},{label:"CAFÉ",src:"/img/gloa-cafe.png",alt:"Matcha-Zubereitung im Café"},{label:"ON THE GO",src:"/img/gloa-on-the-go.png",alt:"Iced Matcha unterwegs in Berlin"},{label:"ICED",src:"/img/gloa-iced.png",alt:"Iced Matcha"},{label:"SOCIAL",src:"/img/gloa-social.png",alt:"Freunde mit Matcha"}];
// TODO: Replace local community items with Instagram Graph API data after account/API credentials are configured.
type CommunityItem={id:string;image:string;href?:string;alt:string}
const communityItems:CommunityItem[]=[{id:"1",image:"/img/gloa-cafe.png",alt:"Matcha-Zubereitung im Café"},{id:"2",image:"/img/gloa-on-the-go.png",alt:"Iced Matcha unterwegs in Berlin"},{id:"3",image:"/img/gloa-iced.png",alt:"Iced Matcha"},{id:"4",image:"/img/gloa-social.png",alt:"Freunde mit Matcha"},{id:"5",image:"/img/gloa-morning.png",alt:"Matcha am Morgen"},{id:"6",image:"/img/gloa-work.png",alt:"Iced Matcha am Arbeitsplatz"}];
function Placeholder({children=""}:{children?:string}){return <span className="placeholder-label">{children}</span>}
function ProductVisual(){return <div className="product-visual lime"><img src="/img/gloa-hero-packaging.png" alt="GLOA Matcha Verpackung" loading="lazy"/></div>}
function ProductCard({onAdd}:{onAdd:()=>void}){return <article className="product-card"><a href="/shop/gloa-matcha" onClick={()=>track("product_view")}><ProductVisual/><div className="product-info"><div><h3>{PRODUCT.name}</h3><p>{PRODUCT.origin} · LATTE + PURE</p></div><strong>BALD DA</strong></div></a><button className="add" onClick={onAdd}>Sag mir Bescheid <span>＋</span></button></article>}
function HowTo(){return <section className="how-to"><div className="section-head"><div><p className="eyebrow">HOW TO GLOA</p><h2>Latte oder Pur.<br/>Mehr brauchst du nicht.</h2></div></div><div className="method-grid"><article><span>01</span><h3>Matcha Latte</h3><ol><li>Matcha dosieren</li><li>Mit Wasser aufschlagen</li><li>Milch oder Pflanzendrink dazu</li><li>Heiß oder iced genießen</li></ol></article><article><span>02</span><h3>Pure Matcha</h3><ol><li>Matcha dosieren</li><li>Mit wenig Wasser glattrühren</li><li>Mit Wasser aufschlagen</li><li>Direkt genießen</li></ol></article></div></section>}
function CommunityFeed(){const [offset,setOffset]=useState(0);const [paused,setPaused]=useState(false);const [animate,setAnimate]=useState(true);const total=communityItems.length;useEffect(()=>{const mq=window.matchMedia("(prefers-reduced-motion: reduce)");if(mq.matches)return;let visible=true;const onVis=()=>{visible=document.visibilityState==="visible"};document.addEventListener("visibilitychange",onVis);const id=setInterval(()=>{if(!paused&&visible)setOffset(p=>p+1)},4500);return()=>{clearInterval(id);document.removeEventListener("visibilitychange",onVis)}},[paused]);useEffect(()=>{if(offset>=total){const t=setTimeout(()=>{setAnimate(false);setOffset(0);requestAnimationFrame(()=>requestAnimationFrame(()=>setAnimate(true)))},400);return()=>clearTimeout(t)}},[offset,total]);const track=[...communityItems,...communityItems.slice(0,4)];return <div className="community-feed" onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)}><div className="community-track" style={{transform:`translateX(-${offset*25}%)`,transition:animate?"transform 400ms ease":"none"}}>{track.map((item,i)=><div key={`cf-${i}`} className="community-card"><img src={item.image} alt={item.alt} loading="lazy"/></div>)}</div></div>}
function Home({onAdd}:{onAdd:()=>void}){return <main><section className="hero"><div className="hero-copy"><p className="eyebrow">MATCHA AUS SHIZUOKA.</p><h1>Matcha.<br/><i>Aber richtig.</i></h1><p className="lead">Aus Shizuoka, Japan. Für Latte, pur, iced oder wie du willst.</p><div className="hero-actions"><a className="cta" href="/shop" onClick={()=>track("shop_click")}>Zum Shop</a><a className="cta secondary" href="/about">GLOA entdecken →</a></div></div><div className="hero-art"><img src="/img/gloa-hero-packaging.png" alt="GLOA Matcha Verpackung" className="hero-img"/><span className="hero-micro">SHIZUOKA / JAPAN</span></div></section><section className="product-intro"><div><p className="eyebrow">MEET YOUR MATCHA.</p><h2>Ein Grün.<br/><i>Viele Momente.</i></h2><p>Aus Shizuoka, Japan. Für Matcha Latte und pur. Easy im Alltag, ehrlich im Produkt.</p><a className="cta" href="/shop">Shop GLOA</a></div><ProductCard onAdd={onAdd}/></section><section className="daily"><div className="daily-copy"><p className="eyebrow">MATCHA FÜR JEDEN TAG</p><h2>Morgens.<br/>Im Meeting.<br/><i>Nachmittags.</i></h2></div><div className="daily-grid">{dailyTiles.map(t=><div className="daily-tile" key={t.label}><img src={t.src} alt={t.alt} loading="lazy"/><span>{t.label}</span></div>)}</div></section><section className="origin"><div><p className="eyebrow">ORIGIN</p><h2>From Shizuoka,<br/><i>Japan.</i></h2></div><div><p>GLOA Matcha kommt aus Shizuoka, Japan. Mehr zum Produzenten, Cultivar und der Ernte teilen wir, sobald alles verifiziert ist.</p><dl><div><dt>ORIGIN</dt><dd>Shizuoka, Japan</dd></div><div><dt>MADE FOR</dt><dd>Latte + pure preparation</dd></div></dl></div></section><HowTo/><JournalGrid/><section className="community"><p className="eyebrow">#gloamatcha</p><h2>Zeig uns<br/><i>deinen Matcha.</i></h2><CommunityFeed/><a href={`https://instagram.com/${BRAND.instagram}`} target="_blank" rel="noopener noreferrer">@gloa.matcha folgen →</a></section><Newsletter/></main>}
function JournalGrid(){return <section className="journal-grid">{articles.map(a=><article key={a.slug}><div className={`journal-img ${a.tone}`}>{a.image?<img src={a.image} alt={a.alt} loading="lazy"/>:<Placeholder/>}</div><p className="eyebrow">{a.type} · {a.time}</p><h2>{a.title}</h2><a href={`/journal/${a.slug}`}>{a.type==="RECIPE"?"Rezept ansehen →":"Weiterlesen →"}</a></article>)}</section>}
function Shop({onAdd}:{onAdd:()=>void}){return <main className="inner"><PageHero index="01" eyebrow="THE GLOA SHOP" title={<>Bald hier.<br/><i>Du als Erstes.</i></>} text="Wir arbeiten noch an den letzten Details. Trag dich auf die Waitlist ein und wir sagen dir Bescheid, sobald es losgeht." tone="shop"/><section className="products inner-products"><div className="product-grid single"><ProductCard onAdd={onAdd}/></div></section></main>}
function ProductPage({onAdd}:{onAdd:()=>void}){return <main className="pdp"><section className="pdp-hero"><ProductVisual/><div><p className="eyebrow">MATCHA · SHIZUOKA</p><h1>{PRODUCT.name}</h1><p>Für Latte und pure Zubereitung.</p><dl><div><dt>Size</dt><dd>folgt</dd></div><div><dt>Price</dt><dd>coming soon</dd></div><div><dt>Origin</dt><dd>{PRODUCT.origin}</dd></div></dl><label>Quantity<input type="number" min="1" defaultValue="1"/></label><button className="cta" onClick={onAdd}>Sag mir Bescheid</button></div></section><section className="pdp-facts"><div><p className="eyebrow">WHAT WE KNOW</p><h2>Clear facts.<br/>Nothing invented.</h2></div><dl><div><dt>USE</dt><dd>Latte + pure preparation</dd></div><div><dt>STORAGE</dt><dd>{PRODUCT.storage}</dd></div><div><dt>TASTE</dt><dd>folgt</dd></div><div><dt>CULTIVAR</dt><dd>folgt</dd></div></dl></section><HowTo/><JournalGrid/></main>}
function PageHero({index,eyebrow,title,text,tone}:{index:string;eyebrow:string;title:React.ReactNode;text:string;tone:string}){return <section className={`inner-hero ${tone}`}><span className="page-index">{index}</span><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="lead">{text}</p></div></section>}
function MatchaPage(){return <main className="matcha-page">
<section className="matcha-hero"><div className="matcha-hero-copy"><p className="eyebrow">UNSER MATCHA</p><h1>Aus Shizuoka.<br/><i>Für deinen Alltag.</i></h1><p className="lead">Was wir über unser Produkt wissen. Was wir noch nicht sagen können. Keine erfundenen Claims. Kein Marketing-Bullshit.</p></div><div className="matcha-hero-visual"><img src="/img/gloa-hero-packaging.png" alt="GLOA Matcha Verpackung"/></div></section>
<section className="matcha-facts"><p className="eyebrow">THE FACTS</p><h2>Was wir<br/><i>wissen.</i></h2><div className="matcha-facts-grid"><div><span>HERKUNFT</span><strong>Shizuoka, Japan</strong></div><div><span>ERNTE</span><strong>2. und 3. Pflückung</strong></div><div><span>VERWENDUNG</span><strong>Latte · Iced · Pur</strong></div><div><span>MINDESTHALTBARKEIT</span><strong>3 Jahre</strong></div><div><span>LAGERUNG</span><strong>Kühl und trocken</strong></div><div><span>LAGER</span><strong>Deutschland</strong></div></div><div className="matcha-facts-secondary"><p>GASTRO-FORMATE · 500 g · 1 kg</p><p>MAHLUNG · Industriell · ca. 6 Monate vor Kauf</p></div></section>
<section className="matcha-transparency"><div className="matcha-transparency-inner"><p className="eyebrow">TRANSPARENZ</p><h2>Was wir noch<br/><i>prüfen.</i></h2><p>Einige Details zum Produkt sind noch nicht vollständig verifiziert. Sobald sie bestätigt sind, ergänzen wir sie hier.</p><div className="matcha-pending-grid">{[["PRODUZENT / FARM","IN PRÜFUNG"],["CULTIVAR","IN PRÜFUNG"],["SINGLE CULTIVAR / BLEND","IN PRÜFUNG"],["GESCHMACKSPROFIL","IN PRÜFUNG"],["BIO-STATUS","IN PRÜFUNG"],["PRODUKTSPEZIFIKATION","IN PRÜFUNG"],["CHARGENANALYSE / COA","IN PRÜFUNG"],["PESTIZIDRÜCKSTÄNDE","UNTERLAGEN IN PRÜFUNG"],["MIKROBIOLOGISCHE ANALYSE","UNTERLAGEN IN PRÜFUNG"],["SCHWERMETALLANALYSE","UNTERLAGEN IN PRÜFUNG"],["MAHLVERFAHREN – DETAILS","IN PRÜFUNG"],["ERNTE- / PRODUKTIONSDATEN","IN PRÜFUNG"]].map(([label,status])=><div key={label}><span>{label}</span><strong>○ {status}</strong></div>)}</div><div className="matcha-price-note"><span>ENDKUNDENPREIS</span><strong>WIRD VOR LAUNCH ERGÄNZT</strong></div><p className="matcha-transparency-note">Wir erfinden nichts. Was hier steht, ist geprüft.</p></div></section>
<section className="matcha-howto"><div className="section-head"><div><p className="eyebrow">HOW TO GLOA</p><h2>Drei Wege.<br/><i>Alle easy.</i></h2></div></div><div className="matcha-method-grid"><article><span>01</span><h3>Matcha Latte</h3><ol><li>Matcha dosieren</li><li>Mit wenig Wasser glatt rühren</li><li>Milch oder Pflanzendrink dazu</li><li>Heiß genießen</li></ol></article><article><span>02</span><h3>Iced Matcha</h3><ol><li>Matcha dosieren</li><li>Mit wenig Wasser glatt rühren</li><li>Über Eis geben</li><li>Milch oder Pflanzendrink dazu</li></ol></article><article><span>03</span><h3>Pure Matcha</h3><ol><li>Matcha dosieren</li><li>Mit wenig Wasser glatt rühren</li><li>Mit Wasser auffüllen</li><li>Direkt genießen</li></ol></article></div></section>
<section className="matcha-image"><img src="/img/gloa-iced.png" alt="Iced Matcha von GLOA"/></section>
<section className="matcha-cta"><h2>Bereit?</h2><div className="matcha-cta-actions"><a className="cta" href="/shop">Zum Shop</a><a className="cta secondary" href="/for-cafes">B2B →</a></div></section>
</main>}
function About(){return <main className="about-page">
<section className="about-hero"><span className="page-index">03</span><div><p className="eyebrow">ÜBER GLOA</p><h1>Good energy.<br/><i>No theatre.</i></h1><p className="lead">GLOA bringt Matcha aus Shizuoka in einen Alltag, der nicht nach Regeln fragt.</p><p className="about-sub-lead">Für Latte, iced, pur oder genau so, wie du ihn magst.</p></div><div className="about-hero-micro"><span>SHIZUOKA / JAPAN</span><span>BERLIN / GERMANY</span><span>EST. 2026</span></div></section>
<section className="about-beliefs"><p className="eyebrow">WE BELIEVE IN</p><div className="about-beliefs-grid"><div className="about-belief"><span>01</span><h2>Gutes Produkt<br/>statt Hype.</h2></div><div className="about-belief"><span>02</span><h2>Echte Leute<br/>statt Bullshit.</h2></div><div className="about-belief accent"><span>03</span><h2>Matcha, der<br/><i>einfach Spaß macht.</i></h2></div></div></section>
<section className="about-why"><div className="about-why-left"><p className="eyebrow">WHY GLOA EXISTS</p><h2>Matcha gehört<br/>nicht in eine<br/><i>Schublade.</i></h2></div><div className="about-why-right"><p>Wir mögen Matcha, aber nicht die Regeln, die manchmal darum gebaut werden.</p><p>GLOA soll unkompliziert funktionieren: im Café, im Büro, unterwegs oder zu Hause.</p><p>Kein Dresscode.<br/>Kein Ritual-Zwang.<br/>Ein gutes Produkt und du entscheidest, was du daraus machst.</p></div></section>
<section className="about-founders"><p className="eyebrow">BEHIND GLOA</p><h2>Vali <span className="about-x">×</span> Poli.</h2><p className="about-founders-lead">Wir bauen GLOA gemeinsam auf.</p><div className="about-founders-text"><p>Von Produkt und Packaging über Brand, Website und Cafés bis zum Launch: GLOA entsteht gerade Schritt für Schritt.</p><p>Wir wollen dabei nicht so tun, als wäre schon alles fertig. Du kannst dabei sein, während es entsteht.</p></div></section>
<section className="about-tiktok"><p className="eyebrow">BUILDING GLOA</p><h2>Begleite uns<br/><i>auf dem Weg.</i></h2><p>Wir bauen GLOA gerade auf.</p><p>Packaging, Produkt, Cafés, Launch und alles dazwischen. Auf TikTok zeigen wir, was hinter der Marke passiert.</p><a className="about-handle" href="https://www.tiktok.com/@gloa.matcha" target="_blank" rel="noopener noreferrer">@gloa.matcha</a><a className="cta cream" href="https://www.tiktok.com/@gloa.matcha" target="_blank" rel="noopener noreferrer">Auf TikTok folgen ↗</a><p className="about-micro">BUILDING IN PUBLIC · BERLIN · 2026</p></section>
<section className="about-final"><h2>Genug über uns.<br/><i>Zeit für Matcha.</i></h2><div className="about-final-actions"><a className="cta cream" href="/shop">Zum Shop</a><a className="cta about-cta-outline" href="/our-matcha">Unser Matcha →</a></div></section>
</main>}
function ForCafes(){useEffect(()=>track("b2b_page_view"),[]);return <main className="business"><section className="b2b-hero"><div><p className="eyebrow">GLOA FOR BUSINESS</p><h1>Matcha for<br/><i>your menu.</i></h1><p>Matcha aus Shizuoka für moderne Menüs.</p><div><a className="cta cream" href="?intent=sample#lead" onClick={()=>track("sample_request_start")}>Sample anfragen</a><a className="cta b2b-outline" href="#calculator">Umsatzpotenzial berechnen →</a></div></div><div className="b2b-visual"><div className="hero-tin"><span>GLOA</span><small>FOR BUSINESS</small></div><Placeholder/></div></section><section className="quick-facts">{["SHIZUOKA, JAPAN","LATTE · ICED · PUR","LAGER IN DEUTSCHLAND","SCHNELLE NACHBESTELLUNG","500 G · 1 KG GASTRO"].map(x=><strong key={x}>{x}</strong>)}</section><section className="behind-bar"><div><p className="eyebrow">FÜR DEINE BAR GEMACHT.</p><h2>Einfach zubereiten.<br/><i>Easy skalieren.</i></h2><p>Classic, iced, Strawberry oder pur — ein Produkt, viele Drinks auf der Karte.</p></div><div className="servings"><span className="eyebrow servings-label">BEISPIELRECHNUNG</span><span><b>3 G</b>PRO DRINK</span><i>→</i><span><b>CA. 333</b>DRINKS / KG</span><small>Beispiel bei 3 g Matcha pro Drink.</small></div></section><BusinessCalculator/><BusinessFaq/></main>}
function BusinessFaq(){const qs:[string,string][]=[["Wo kommt GLOA Matcha her?","Shizuoka, Japan."],["Ist GLOA für Matcha Latte geeignet?","Ja. Das Produkt ist für Latte, iced und pur geeignet."],["Welche Großhandelsformate gibt es?","500 g und 1 kg Gastroformate."],["Habt ihr Lager in Deutschland?","Ja. Bestand in Deutschland."],["Wie schnell liefert ihr?","Lieferzeit und Verfügbarkeit bestätigen wir bei Bestellung."],["Wie viele Drinks bekomme ich aus 1 kg?","Abhängig von der Dosierung: Bei 2 g pro Drink ca. 500 Drinks, bei 3 g ca. 333 Drinks, bei 4 g ca. 250 Drinks. Mengenbeispiele."],["Was kostet es im Großhandel?","Unsere B2B-Konditionen werden individuell mit dir abgestimmt. Frag sie direkt über das B2B-Formular an."],["Was ist die regelmäßige Belieferung?","Ein flexibles Bezugsmodell mit monatlicher Lieferung und 5 % Preisvorteil. Mindestlaufzeit 3 Monate, danach monatlich kündbar."],["Wie funktioniert die 12-Monats-Partnerschaft?","Du vereinbarst eine monatliche Mindestabnahme für 12 Monate und erhältst 10 % Preisvorteil. Lieferung und Abrechnung erfolgen monatlich."],["Muss ich beim Jahresmodell alles im Voraus bezahlen?","Nein. Die Abrechnung erfolgt monatlich. Du zahlst nur die jeweils gelieferte Menge."],["Kann ich mehr als die vereinbarte Menge bestellen?","Ja. Zusätzliche Mengen können jederzeit angefragt werden – zum gleichen Kilopreis deines Modells."],["Was passiert, wenn ich noch nicht weiß, wie viel Matcha ich brauche?","Starte mit einer Einzelbestellung oder einem Sample. Sobald du deinen Bedarf besser einschätzen kannst, kannst du jederzeit auf ein Bezugsmodell wechseln."]];return <section className="faq"><p className="eyebrow">B2B FAQ</p><h2>Fragen?<br/><i>Antworten.</i></h2>{qs.map(([q,a])=><details key={q}><summary>{q}<span>＋</span></summary><p>{a}</p></details>)}</section>}
function Journal(){return <main className="inner"><PageHero index="04" eyebrow="GLOA JOURNAL" title={<>Things we make.<br/><i>Places we like.</i></>} text="Rezepte, Matcha, Café-Kultur und GLOA Stories." tone="journal"/><div className="filters"><button>ALL</button><button>RECIPES</button><button>MATCHA</button><button>CULTURE</button><button>CAFÉS</button></div><JournalGrid/></main>}
function Article({slug}:{slug:string}){const a=articles.find(x=>x.slug===slug)||articles[0];return <main className="article"><p className="eyebrow">{a.type} · {a.time}</p><h1>{a.title}</h1><div className={`article-image ${a.tone}`}><Placeholder/></div><article><h2>Dieser Artikel ist noch in Arbeit.</h2><p>Inhalt kommt, sobald Rezepte und Stories final abgestimmt sind.</p><a href="/journal">← Back to Journal</a></article></main>}
function Contact(){return <main className="inner"><PageHero index="05" eyebrow="KONTAKT" title={<>Schreib<br/><i>uns.</i></>} text="Wähl den richtigen Weg und deine Nachricht landet da, wo sie hingehört." tone="contact"/><section className="contact-choices"><a href="#customer"><span>CUSTOMER</span><h2>Fragen zu<br/>Produkt & Bestellung.</h2><b>Schreib uns</b></a><a href="/for-cafes"><span>BUSINESS</span><h2>Großhandel,<br/>Samples & Cafés.</h2><b>Zum B2B-Bereich →</b></a></section><form id="customer" className="customer-form" onSubmit={e=>e.preventDefault()}><label>Name<input required/></label><label>Email<input required type="email"/></label><label>Message<textarea required/></label><button className="cta">Nachricht senden</button></form></main>}
function Legal({route}:{route:string}){const title:Record<string,string>={impressum:"Impressum",datenschutz:"Datenschutz",agb:"Allgemeine Geschäftsbedingungen",widerruf:"Widerruf",versand:"Versandinformationen"};return <main className="legal-page"><p className="eyebrow">LEGAL</p><h1>{title[route]||"Legal"}</h1><div className="legal-placeholder"><h2>Rechtlicher Inhalt ausstehend.</h2><p>Vor dem öffentlichen Shop-Launch muss dieser Inhalt von GLOA beziehungsweise einer qualifizierten Rechtsberatung bereitgestellt und geprüft werden.</p></div></main>}
export function GloaSite({route}:{route:string}){const [cart,setCart]=useState(false);const add=()=>{track("add_to_cart");setCart(true)};let page:React.ReactNode;if(route==="home")page=<Home onAdd={add}/>;else if(route==="shop")page=<Shop onAdd={add}/>;else if(route==="shop/gloa-matcha")page=<ProductPage onAdd={add}/>;else if(route==="our-matcha")page=<MatchaPage/>;else if(route==="about")page=<About/>;else if(route==="for-cafes"||route==="wholesale")page=<ForCafes/>;else if(route==="journal")page=<Journal/>;else if(route.startsWith("journal/"))page=<Article slug={route.split("/")[1]}/>;else if(route==="contact")page=<Contact/>;else if(["impressum","datenschutz","agb","widerruf","versand"].includes(route))page=<Legal route={route}/>;else page=<main className="not-found"><h1>404</h1><a href="/">Back to GLOA →</a></main>;return <><Header onCart={()=>setCart(true)}/>{page}<Footer/>{cart&&<div className="cart-backdrop" onClick={()=>setCart(false)}><aside className="cart" onClick={e=>e.stopPropagation()} aria-modal="true" role="dialog" aria-label="Warenkorb"><button onClick={()=>setCart(false)} aria-label="Schließen">×</button><p className="eyebrow">WAITLIST</p><h2>Fast<br/>soweit.</h2><p>Lass uns deine Mail da und du erfährst es als Erstes.</p><a href="/contact" className="cta">Sag mir Bescheid</a></aside></div>}</>}
