/** Permanent local-only verification: real PostgreSQL/routes, doubled providers, no Production access. */
import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import {createRequire} from 'node:module';import {spawn} from 'node:child_process';import {createServer,request as httpRequest} from 'node:http';import {createHmac,randomUUID} from 'node:crypto';import assert from 'node:assert/strict';
const out=path.resolve('outputs/final-verification/reality');fs.mkdirSync(out,{recursive:true});
const baseline={database:process.env.GLOA_ATOMIC_LOCAL_DATABASE};
const {sql}=await import('../helpers/affiliateAtomicDatabase.mjs');
if(!/^gloa_073_[a-f0-9]+$/.test(baseline.database))throw Error('Disposable database only');
const require=createRequire(import.meta.url),ts=require('typescript'),cache=new Map(),results=[],httpErrors=[];
const jwtSecret='local-audit-only-jwt-secret-never-a-production-credential',sessionSecret='local-audit-session-only-secret-xxxxxxxxxxxxxxxx';
const owner=randomUUID(),viewer=randomUUID(),adminActor=randomUUID(),email='audit-owner-'+owner+'@example.invalid',viewerEmail='audit-viewer-'+viewer+'@example.invalid';
const adminEmail='audit-admin-'+adminActor+'@example.invalid';
sql(`insert into auth.users(id,email) values ('${owner}','${email}'),('${viewer}','${viewerEmail}'),('${adminActor}','${adminEmail}'); insert into admin_users(user_id,email,display_name,role,is_active) values ('${owner}','${email}','Audit owner','owner',true),('${viewer}','${viewerEmail}','Audit viewer','viewer',true),('${adminActor}','${adminEmail}','Audit admin','admin',true);`);
const jwt=role=>{const a=Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url'),b=Buffer.from(JSON.stringify({role,exp:Math.floor(Date.now()/1000)+3600})).toString('base64url');return a+'.'+b+'.'+createHmac('sha256',jwtSecret).update(a+'.'+b).digest('base64url');};
const localEnvironment={ADMIN_SESSION_SECRET:sessionSecret,ADMIN_EMAILS:[email,viewerEmail,adminEmail].join(','),SUPABASE_SECRET_KEY:jwt('service_role'),STRIPE_SECRET_KEY:'',RESEND_API_KEY:''};
const localBuild={VITE_SUPABASE_URL:'http://127.0.0.1:55475',VITE_SUPABASE_PUBLISHABLE_KEY:jwt('anon')};
const originalFetch=globalThis.fetch;
const localFetch=(input,init)=>{const url=new URL(typeof input==='string'?input:input.url??String(input));if(!['127.0.0.1','localhost'].includes(url.hostname))throw Error('Audit blocked external network');return originalFetch(input,init);};globalThis.fetch=localFetch;
function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file).exports;const loadedModule={exports:{}};cache.set(file,loadedModule);const source=fs.readFileSync(file,'utf8').replaceAll('import.meta.env','__localBuildEnvironment');const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;const localRequire=name=>{if(name.startsWith('.')){let target=path.resolve(path.dirname(file),name);if(!path.extname(target))target+='.ts';return load(target);}return require(name);};vm.runInNewContext(js,{module:loadedModule,exports:loadedModule.exports,require:localRequire,Response,Request,Headers,console,URL,Date,Intl,Buffer,process:{env:localEnvironment},__localBuildEnvironment:localBuild,fetch:localFetch,setTimeout,clearTimeout,AbortController,AbortSignal},{filename:file});return loadedModule.exports;}
fs.writeFileSync(path.join(out,'postgrest.conf'),`db-uri = "postgres://postgres@127.0.0.1:55472/${baseline.database}?sslmode=disable&gssencmode=disable&connect_timeout=5"\ndb-schemas = "public"\ndb-anon-role = "anon"\njwt-secret = "${jwtSecret}"\nserver-host = "127.0.0.1"\nserver-port = 18076\n`);
const env=Object.fromEntries(Object.entries(process.env).filter(([k])=>!/^path$/i.test(k)&&!/^PG/i.test(k)));env.Path='C:/Program Files/PostgreSQL/17/bin;'+(process.env.Path??process.env.PATH??'');
env.PGSSLMODE='disable';env.PGGSSENCMODE='disable';env.PGCONNECT_TIMEOUT='5';
const pg=spawn(path.resolve(process.env.GLOA_POSTGREST_BINARY ?? 'outputs/postgrest-v14.18/postgrest.exe'),[path.join(out,'postgrest.conf'),'+RTS','-N1','-RTS'],{windowsHide:true,env});pg.stdout.on('data',c=>fs.appendFileSync(path.join(out,'postgrest.log'),c));pg.stderr.on('data',c=>fs.appendFileSync(path.join(out,'postgrest.log'),c));
const proxy=createServer((req,res)=>{if(!req.url.startsWith('/rest/v1/')){res.writeHead(404);res.end();return;}const next=httpRequest({host:'127.0.0.1',port:18076,path:req.url.slice('/rest/v1'.length),method:req.method,headers:req.headers},reply=>{res.writeHead(reply.statusCode,reply.headers);reply.pipe(res);});next.on('error',e=>{res.writeHead(503);res.end(String(e));});req.pipe(next);});
const api=createServer(async(req,res)=>{try{const bytes=[];for await(const chunk of req)bytes.push(chunk);const route=req.url;if(!/^\/api\/(admin\/(creators|portal|documents|finance|dashboard-summary|shipping|customer-rights|costs|activity)|affiliate)$/.test(route)){res.writeHead(404);res.end();return;}const body=Buffer.concat(bytes).toString();const r=await load('app'+route+'/route.ts').POST(new Request('http://127.0.0.1:55477'+route,{method:req.method,headers:req.headers,body:body||undefined}));res.writeHead(r.status,Object.fromEntries(r.headers));res.end(await r.text());}catch(error){httpErrors.push(String(error));res.writeHead(500);res.end(JSON.stringify({error:String(error)}));}});
const listen=(server,port)=>new Promise((resolve,reject)=>{server.once('error',reject);server.listen(port,'127.0.0.1',resolve);});
const inventory=()=>sql("select jsonb_build_object('items',(select coalesce(jsonb_agg(to_jsonb(i) order by id),'[]') from inventory_items i),'movements',(select coalesce(jsonb_agg(to_jsonb(m) order by id),'[]') from inventory_movements m))");
const beforeInventory=inventory(),session=load('lib/adminSession.ts');
const cookies={owner:session.ADMIN_SESSION_COOKIE+'='+session.issueAdminSession(owner,email,Date.now(),sessionSecret),viewer:session.ADMIN_SESSION_COOKIE+'='+session.issueAdminSession(viewer,viewerEmail,Date.now(),sessionSecret),admin:session.ADMIN_SESSION_COOKIE+'='+session.issueAdminSession(adminActor,adminEmail,Date.now(),sessionSecret)};
async function call(route,body,role='owner'){const r=await localFetch('http://127.0.0.1:55477/api/'+route,{method:'POST',headers:{'Content-Type':'application/json',...(cookies[role]?{cookie:cookies[role]}:{})},body:JSON.stringify(body)});return {status:r.status,data:await r.json()};}
async function check(name,fn){try{const details=await fn();results.push({name,pass:true,details:details??null});console.log('PASS',name);}catch(error){results.push({name,pass:false,evidence:String(error)});console.log('FAIL',name,String(error));throw error;}}
let auditProviderCalls=0;const auditProviderStates=new Map();load('lib/stripe.ts').getStripeClient=()=>({subscriptions:{retrieve:async id=>auditProviderStates.get(id)??{id,cancel_at:null},update:async(id,p)=>{auditProviderCalls++;const state={id,...p};auditProviderStates.set(id,state);return state;}}});
let creator,ugc,doc,link,order;
try{
 await listen(proxy,55475);await listen(api,55477);let ready=false;for(let n=0;n<60;n++){try{const r=await localFetch('http://127.0.0.1:18076/');if(r.status===200){ready=true;break;}}catch{/* Waiting for local server readiness. */}await new Promise(r=>setTimeout(r,200));}assert.ok(ready,'Local PostgREST readiness required; do not classify infrastructure failures as application defects');
 await check('Real session + fresh admin_users role gate: anonymous 401, viewer write 403, viewer finance 403',async()=>{assert.equal((await call('admin/creators',{action:'list'},'none')).status,401);assert.equal((await call('admin/creators',{action:'create_creator',displayName:'Refused',email:'refused@example.invalid'},'viewer')).status,403);assert.equal((await call('admin/finance',{action:'summary'},'viewer')).status,403);assert.equal((await call('admin/creators',{action:'list'},'admin')).status,200);});
 await check('Creator create -> real API -> PostgreSQL -> API list read-back',async()=>{const r=await call('admin/creators',{action:'create_creator',displayName:'Reality Audit Creator',email:'reality-creator-2e83313e319cf9536a1b58ec@example.invalid'});assert.equal(r.status,200,JSON.stringify(r));creator=r.data.creatorId;const list=await call('admin/creators',{action:'list'});assert.equal(list.status,200);const row=list.data.creators.find(c=>c.id===creator);assert.equal(row.status,'prospect');return row;});
 await check('Creator required-field/duplicate-email database protection',async()=>{for(const body of [{displayName:'',email:'empty@example.invalid'},{displayName:'Duplicate',email:'reality-creator-2e83313e319cf9536a1b58ec@example.invalid'}]){const r=await call('admin/creators',{action:'create_creator',...body});assert.notEqual(r.status,200);assert.ok(r.data.error);returnValue(r);}function returnValue(r){results.push({name:'Creator invalid input response',pass:[400,409].includes(r.status),details:r});}});
 await check('Creator active status and simultaneous affiliate/influencer/ugc roles',async()=>{assert.equal((await call('admin/creators',{action:'update_creator',creatorId:creator,status:'active'})).status,200);for(const role of ['affiliate','ugc_creator','influencer'])assert.equal((await call('admin/creators',{action:'add_role',creatorId:creator,role})).status,200);const list=await call('admin/creators',{action:'list'});assert.equal(list.data.roles.filter(r=>r.creator_id===creator).length,3);});
 await check('Inline percentage link and fixed code -> RPC -> rule/audit -> API read-back',async()=>{for(const [type,value,bp,cents,reference] of [['percentage','12,5',1250,null,'reality-link-2e83313e319cf9536a1b58ec'],['percentage','7,25',725,null,'reality-other-2e83313e319cf9536a1b58ec'],['fixed','5,00',null,500,'REALITY500-2e83313e319cf9536a1b58ec'],['fixed','0,29',null,29,'REALITY29-2e83313e319cf9536a1b58ec']]){const action=type==='percentage'?'create_affiliate_link':'create_affiliate_code';const body={action,creatorId:creator,slug:reference,code:reference,commissionMode:'inline',calculationType:type,commissionValue:value,base:'order_gross',status:'active',startsAt:'2020-01-01T00:00:00Z'};const r=await call('admin/creators',body);assert.equal(r.status,200,JSON.stringify(r));if(reference==='reality-link-2e83313e319cf9536a1b58ec')link=r.data.id;const list=await call('admin/creators',{action:'list'});const relation=[...list.data.links,...list.data.codes].find(c=>c.id===r.data.id);const rule=list.data.rules.find(c=>c.id===relation.commission_rule_id);assert.equal(rule.percent_basis_points,bp);assert.equal(rule.fixed_cents,cents);assert.equal(Number(sql(`select count(*) from admin_activity_log where entity_id='${r.data.id}' and action='affiliate.created'`)),1);}});
 await check('Inline invalid percentages/fixed/creator/rule/duplicates are rejected without new rules',async()=>{const baseline=sql('select count(*) from creator_commission_rules');const valid={action:'create_affiliate_link',creatorId:creator,slug:'reality-invalid',commissionMode:'inline',calculationType:'percentage',commissionValue:'12,5',base:'order_gross'};for(const changes of [{commissionValue:'100,01'},{commissionValue:'0'},{calculationType:'fixed',commissionValue:'-1'},{calculationType:'fixed',commissionValue:'0'},{creatorId:randomUUID()},{commissionMode:'existing',commissionRuleId:randomUUID()},{slug:'reality-link-2e83313e319cf9536a1b58ec',commissionValue:'17'},{action:'create_affiliate_code',code:'REALITY500-2e83313e319cf9536a1b58ec',calculationType:'fixed',commissionValue:'17'}]){const r=await call('admin/creators',{...valid,...changes});assert.ok([400,409].includes(r.status),JSON.stringify(r));}assert.equal(sql('select count(*) from creator_commission_rules'),baseline);});
 await check('Actual public resolver link/code, paused/expired/inactive creator, no creator/rule disclosure',async()=>{let r=await call('affiliate',{action:'resolve_link',slug:'reality-link-2e83313e319cf9536a1b58ec',creator_id:randomUUID(),commissionCents:99999},'none');assert.equal(r.data.result,'active');assert.equal(r.data.creator_id,undefined);assert.equal(r.data.commissionCents,undefined);assert.equal((await call('affiliate',{action:'resolve_code',code:'REALITY500-2e83313e319cf9536a1b58ec'},'none')).data.result,'active');assert.equal((await call('admin/creators',{action:'update_affiliate',id:link,type:'link',status:'paused'})).status,200);assert.notEqual((await call('affiliate',{action:'resolve_link',slug:'reality-link-2e83313e319cf9536a1b58ec'},'none')).data.result,'active');await call('admin/creators',{action:'update_affiliate',id:link,type:'link',status:'active'});await call('admin/creators',{action:'update_creator',creatorId:creator,status:'paused'});assert.notEqual((await call('affiliate',{action:'resolve_link',slug:'reality-link-2e83313e319cf9536a1b58ec'},'none')).data.result,'active');await call('admin/creators',{action:'update_creator',creatorId:creator,status:'active'});sql(`update affiliate_links set ends_at='2021-01-01' where id='${link}'`);assert.notEqual((await call('affiliate',{action:'resolve_link',slug:'reality-link-2e83313e319cf9536a1b58ec'},'none')).data.result,'active');sql(`update affiliate_links set ends_at=null where id='${link}'`);});
 await check('Paid order -> server helper -> real attribution/commission -> Finance/Creator read-back; replay',async()=>{order=randomUUID();sql(`insert into orders(id,customer_type,status,payment_status,customer_snapshot,placed_at,total_gross_cents,total_net_cents,tax_total_cents,subtotal_gross_cents,subtotal_net_cents,shipping_gross_cents,shipping_net_cents) values ('${order}','private','confirmed','paid','{"name":"Reality Customer","email":"reality-customer@example.invalid"}',now(),10000,9346,654,9000,8400,1000,946);select record_order_payment_event('${order}');select record_order_payment_event('${order}');`);const helpers=load('lib/creatorAffiliate.ts');const r=await helpers.attributeOrderToCreator({orderId:order,source:'affiliate_link',reference:'reality-link-2e83313e319cf9536a1b58ec'});assert.equal(r.commission_cents,1250,JSON.stringify(r));await helpers.attributeOrderToCreator({orderId:order,source:'affiliate_link',reference:'reality-link-2e83313e319cf9536a1b58ec'});assert.equal(sql(`select count(*) from creator_commissions where order_id='${order}' and kind='earned'`),'1');const creatorList=await call('admin/creators',{action:'list'});assert.ok(creatorList.data.commissions.some(c=>c.order_id===order&&c.amount_cents===1250));const finance=await call('admin/finance',{action:'list',period:'year'});assert.equal(finance.status,200);assert.equal(finance.data.events.filter(e=>e.order_id===order&&e.kind==='order_payment').length,1);});
 await check('Refund helper writes proportional reversal once and original remains unchanged',async()=>{const helpers=load('lib/creatorAffiliate.ts');const original=sql(`select to_jsonb(c) from creator_commissions c where order_id='${order}' and kind='earned'`);sql(`select record_order_refund_event('${order}',2500)`);const r=await helpers.reverseCreatorCommissionForRefund({orderId:order,refundedTotalCents:2500});assert.equal(r.reversed_cents,313,JSON.stringify(r));await helpers.reverseCreatorCommissionForRefund({orderId:order,refundedTotalCents:2500});assert.equal(sql(`select count(*) from creator_commissions where order_id='${order}' and kind='reversal'`),'1');assert.equal(sql(`select to_jsonb(c) from creator_commissions c where order_id='${order}' and kind='earned'`),original);});
 await check('UGC create/update real API and Creator read-back',async()=>{const r=await call('admin/creators',{action:'create_ugc_assignment',creatorId:creator,title:'Reality Reel',deliverableType:'reel',feeCents:500,dueDate:new Date().toISOString().slice(0,10),usageRightsNote:'Synthetic stored note'});assert.equal(r.status,200,JSON.stringify(r));ugc=r.data.assignmentId;const updated=await call('admin/creators',{action:'update_ugc',assignmentId:ugc,status:'submitted',contentUrl:'https://example.invalid/reel',usageRightsNote:'Synthetic stored note'});assert.equal(updated.status,200);const list=await call('admin/creators',{action:'list'});assert.equal(list.data.ugcAssignments.find(a=>a.id===ugc).status,'submitted');});
 await check('Private document metadata + association -> real API -> related context read-back; replay',async()=>{const r=await call('admin/documents',{action:'create_document',title:'Reality Private Receipt',kind:'expense_receipt',storagePath:'synthetic/private.pdf'});assert.equal(r.status,200,JSON.stringify(r));doc=r.data.documentId;const body={action:'link_document',documentId:doc,entityType:'order',entityId:order};assert.equal((await call('admin/documents',body)).status,200);assert.equal((await call('admin/documents',body)).status,200);const context=await call('admin/portal',{action:'context',entity:'order',id:order});assert.equal(context.status,200);assert.equal(context.data.documents.filter(d=>d.document_id===doc).length,1);});
 await check('Global authorized search retrieves actual persisted Creator/order/code and navigation context',async()=>{for(const [term,entity] of [['Reality Audit','creators'],['reality-customer','orders'],['REALITY500-2e83313e319cf9536a1b58ec','affiliate_codes']]){const r=await call('admin/portal',{action:'search',search:term});assert.equal(r.status,200,JSON.stringify(r));assert.ok(r.data.results.some(v=>v.entity===entity&&v.area&&v.tab),JSON.stringify(r));}});
 await check('Dashboard real counts/Finance agree and unknown fee/cost remains unknown',async()=>{const dashboard=await call('admin/dashboard-summary',{period:'year'}),finance=await call('admin/finance',{action:'summary',period:'year'});assert.equal(dashboard.status,200);assert.equal(finance.status,200);assert.deepEqual(dashboard.data.warnings,[]);assert.equal(dashboard.data.business.incomeCents,finance.data.summary.incomeCents);assert.equal(dashboard.data.business.refundCents,finance.data.summary.refundCents);assert.equal(finance.data.summary.providerFeeCents,null);return {counts:dashboard.data.summary,finance:finance.data.summary};});
 await check('Affiliate audit read-back and identical API replay does not duplicate audit',async()=>{const before=sql(`select count(*) from admin_activity_log where entity_id='${link}'`);const r=await call('admin/creators',{action:'create_affiliate_link',creatorId:creator,slug:'reality-link-2e83313e319cf9536a1b58ec',commissionMode:'inline',calculationType:'percentage',commissionValue:'12,5',base:'order_gross',status:'active',startsAt:'2020-01-01T00:00:00Z'});assert.equal(r.status,200);assert.equal(sql(`select count(*) from admin_activity_log where entity_id='${link}'`),before);const activity=await call('admin/activity',{action:'list'});assert.equal(activity.status,200);return {auditCount:before};});
 await check('Real local anon API cannot write protected Creator tables',async()=>{const r=await localFetch('http://127.0.0.1:55475/rest/v1/creators',{method:'POST',headers:{Authorization:'Bearer '+jwt('anon'),'Content-Type':'application/json'},body:JSON.stringify({display_name:'forged',email:'forged@example.invalid'})});assert.ok([401,403].includes(r.status));return r.status;});
 await check('Expense API -> audited writer -> Finance export read-back',async()=>{const operationId=randomUUID();const body={action:'record_expense',occurredOn:new Date().toISOString().slice(0,10),category:'other_direct',grossCents:500,description:'Reality UGC expense',channel:'b2c',paymentStatus:'paid',orderId:order,ugcAssignmentId:ugc,operationId};const r=await call('admin/costs',body);assert.equal(r.status,200,JSON.stringify(r));const exported=await call('admin/finance',{action:'export',period:'year'});assert.ok(exported.data.expenses.some(e=>e.description===body.description));assert.equal(sql(`select count(*) from admin_activity_log where operation_id='${operationId}' and module='finance' and action='expense_recorded'`),'1');assert.equal(sql(`select count(*) from admin_activity_log where operation_id='${operationId}' and module='finance' and action='expense_ugc_associated'`),'1');});
 await check('UGC expense association is persisted by the expense API',()=>{const row=JSON.parse(sql("select to_jsonb(e) from business_expenses e where description='Reality UGC expense' order by created_at desc limit 1"));assert.equal(row.ugc_assignment_id,ugc,'Submitted ugcAssignmentId is ignored by existing API/writer');});
 await check('Creator operation appears in Activity audit',()=>{assert.ok(Number(sql(`select count(*) from admin_activity_log where module='creator' and entity_id='${creator}'`))>0,'Creator profile/role writes create no activity record');});
 await check('Updating a missing Creator reports failure instead of false success',async()=>{const r=await call('admin/creators',{action:'update_creator',creatorId:randomUUID(),status:'active'});assert.equal(r.status,404,JSON.stringify(r));});
 await check('Dashboard forced source failure stays unknown, never fake zero',async()=>{sql('revoke select on creator_applications from service_role');try{const r=await call('admin/dashboard-summary',{period:'year'});assert.equal(r.status,200);assert.equal(r.data.summary.creatorApplicationsPending,null);assert.ok(r.data.warnings.includes('creator_applications'));}finally{sql('grant select on creator_applications to service_role');}});
 await check('Forced real Finance insert failure leaves zero ledger rows; helper returns null',async()=>{const failedOrder=randomUUID();sql(`insert into orders(id,customer_type,status,payment_status,customer_snapshot,placed_at,total_gross_cents) values ('${failedOrder}','private','confirmed','paid','{}',now(),500); create function public.reality_fail_finance() returns trigger language plpgsql as $$begin raise exception 'AUDIT forced Finance failure'; end$$;create trigger reality_fail_finance before insert on financial_events for each row execute function public.reality_fail_finance();`);try{const result=await load('lib/financeRecording.ts').recordOrderPaymentEvent(failedOrder);assert.equal(result,null);assert.equal(sql(`select count(*) from financial_events where order_id='${failedOrder}'`),'0');return {result,ledgerRows:0,callerMustCheckNull:true};}finally{sql('drop trigger reality_fail_finance on financial_events;drop function public.reality_fail_finance()');}});
 await check('Public subscription termination must reach provider or remain retryable',async()=>{const sub=randomUUID(),termination=randomUUID(),stripeId='sub_audit_'+sub;sql(`insert into subscriptions(id,user_id,plan_id,status,customer_snapshot,shipping_address_snapshot,billing_address_snapshot,plan_snapshot,current_period_start,current_period_end,last_paid_period_end,stripe_subscription_id) values ('${sub}','${owner}',(select id from b2c_subscription_plans limit 1),'active','{}','{}','{}','{}',now()-interval '7 days',now()+interval '21 days',now()+interval '21 days','${stripeId}');insert into termination_requests(id,termination_kind,customer_name,contract_reference,contact_email,contract_kind,resolved_subscription_id) values ('${termination}','ordinary','Local customer','${stripeId}','termination@example.invalid','subscription_4w','${sub}');`);const r=await call('admin/customer-rights',{action:'execute_subscription_termination',terminationId:termination});assert.equal(r.status,200,JSON.stringify(r));assert.ok(['scheduled','already_scheduled'].includes(r.data.result));let providerWrites=0;const outcome=await load('lib/subscriptionCancellation.ts').applyDeferredCancellationFromRenewal({subscriptions:{update:async()=>{providerWrites++;}}},stripeId);const state=JSON.parse(sql(`select jsonb_build_object('cancel_at',cancel_at,'effective',cancellation_effective_at) from subscriptions where id='${sub}'`));results.push({name:'Public termination observed provider/result state',pass:true,details:{providerWrites,outcome,state,response:r.data}});assert.ok(auditProviderCalls>0 && outcome==='already_scheduled','Provider must have accepted the cancellation before retries skip it');});
 await check('Inventory quantities and complete movements unchanged across API workflow',()=>{assert.equal(inventory(),beforeInventory);});
 await check('No unexpected HTTP/runtime exceptions',()=>{assert.deepEqual(httpErrors,[]);});
}finally{api.close();proxy.close();pg.kill();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({database:baseline.database,results,httpErrors},null,2));}
console.log(JSON.stringify({total:results.length,pass:results.filter(r=>r.pass).length,fail:results.filter(r=>!r.pass).length,artifact:path.join(out,'results.json')}));
