import type Stripe from "stripe";

/**
 * Every decision the annual later-instalment billing makes, and none of
 * the side effects (Package 5D).
 *
 * A LEAF: type-only imports, no relative value import, no database, no
 * network, no Stripe client, no clock. The flow lives in
 * lib/b2bRuntime.ts and its wiring in lib/b2bRuntimeDeps.ts.
 *
 * ── WHAT THIS FILE REFUSES TO DO ──────────────────────────────
 *
 * It computes no net amount and picks no due date. Migration 062 froze
 * the canonical allocation at activation and 063 owns the due rule; this
 * module turns one already-decided instalment into Stripe parameters,
 * and adds the VAT through the one tax authority.
 */

/* ── The routing key for an ANNUAL invoice ──────────────────── */

/**
 * THE KEY THAT MAKES AN ANNUAL INVOICE RECOGNISABLE.
 *
 * Restated here rather than imported from lib/b2bWebhookRules.ts,
 * exactly as that module restates the checkout key: a value import
 * between two sibling leaves would make both unloadable by the test
 * runner. The focused suite asserts the two agree.
 *
 * An annual instalment invoice is created by GLOA and carries this key
 * in its OWN metadata. A monthly invoice is generated by Stripe from a
 * subscription and carries no GLOA metadata at all - its agreement is
 * found through the SUBSCRIPTION's metadata instead. That difference is
 * what separates the two B2B invoice populations without either having
 * to know about the other.
 */
export const B2B_INVOICE_AGREEMENT_METADATA_KEY = "gloa_b2b_agreement_id";

/** Which instalment of the schedule this invoice collects. */
export const B2B_INVOICE_INSTALMENT_METADATA_KEY = "gloa_b2b_instalment_number";

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export type B2bAnnualInvoiceRouting =
  /** Not a GLOA-issued annual instalment invoice. */
  | { kind: "not_annual" }
  | { kind: "annual"; agreementId: string; instalmentNumber: number }
  /**
   * Annual by the routing key, but unusable. NOT "not annual": an
   * invoice carrying an agreement id IS an annual instalment, and
   * letting it fall through would settle a business contract through a
   * handler written for something else.
   */
  | { kind: "malformed"; reason: string };

/**
 * Decides whether a Stripe Invoice is a GLOA annual instalment.
 *
 * Reads the INVOICE's own metadata, which only this package ever writes.
 * A consumer subscription invoice, a B2B monthly invoice and a one-off
 * invoice all answer not_annual and keep their existing handlers.
 */
export function routeB2bAnnualInvoice(
  metadata: Stripe.Metadata | Record<string, unknown> | null | undefined
): B2bAnnualInvoiceRouting {
  const raw = (metadata ?? {}) as Record<string, unknown>;
  const agreementId = raw[B2B_INVOICE_AGREEMENT_METADATA_KEY];

  if (typeof agreementId !== "string" || agreementId.trim() === "") {
    return { kind: "not_annual" };
  }
  if (!UUID_RE.test(agreementId)) {
    return { kind: "malformed", reason: `${B2B_INVOICE_AGREEMENT_METADATA_KEY} is not a uuid` };
  }

  const rawNumber = raw[B2B_INVOICE_INSTALMENT_METADATA_KEY];
  const instalmentNumber = typeof rawNumber === "string" ? Number(rawNumber) : rawNumber;
  if (typeof instalmentNumber !== "number"
    || !Number.isInteger(instalmentNumber)
    || instalmentNumber < 2
    || instalmentNumber > 4) {
    // 2..4: instalment 1 is settled at activation and never invoiced,
    // and the approved schedules are 1, 2 and 4.
    return { kind: "malformed", reason: `${B2B_INVOICE_INSTALMENT_METADATA_KEY} is not an invoiceable instalment` };
  }

  return { kind: "annual", agreementId, instalmentNumber };
}

/* ── Idempotency ────────────────────────────────────────────── */

/**
 * The Stripe idempotency keys for one instalment's invoice and its item.
 *
 * DETERMINISTIC, derived only from the agreement uuid and the instalment
 * number. This is the crash-safety half of Package 5D: if the server
 * creates the invoice and dies before recording it, the next cron run
 * sends the SAME key and Stripe replays the original response instead of
 * minting a second invoice. Migration 063's unique
 * b2b_payment_schedule_stripe_invoice_id_key is the other half.
 *
 * No email, no name, no amount - an idempotency key is echoed in
 * Stripe's logs and is not a place for personal data.
 */
export function b2bInstalmentInvoiceIdempotencyKey(
  agreementId: string,
  instalmentNumber: number
): string {
  return `gloa-b2b-invoice-${agreementId}-${instalmentNumber}`;
}

export function b2bInstalmentItemIdempotencyKey(
  agreementId: string,
  instalmentNumber: number
): string {
  return `gloa-b2b-invoice-item-${agreementId}-${instalmentNumber}`;
}

/* ── The Stripe parameters ──────────────────────────────────── */

export type B2bInstalmentCharge = {
  netCents: number;
  taxCents: number;
  grossCents: number;
  taxRatePercent: number;
};

export type B2bInstalmentInvoiceInput = {
  agreementId: string;
  instalmentNumber: number;
  instalmentCount: number;
  stripeCustomerId: string;
  currency: string;
  charge: B2bInstalmentCharge;
};

/**
 * The invoice item: one line, the instalment's GROSS.
 *
 * GROSS, because B2B pricing is net-origin and lib/tax.ts has already
 * produced the final figure. Stripe is not asked to compute any tax -
 * there is deliberately no automatic_tax and no tax_behavior anywhere in
 * this flow, because a second opinion about VAT is exactly the thing
 * migration 060 refuses to store.
 */
export function buildB2bInstalmentItemParams(
  input: B2bInstalmentInvoiceInput
): Stripe.InvoiceItemCreateParams {
  return {
    customer: input.stripeCustomerId,
    currency: input.currency.toLowerCase(),
    amount: input.charge.grossCents,
    description:
      `GLOA Matcha B2B – Rate ${input.instalmentNumber} von ${input.instalmentCount}`,
    metadata: b2bInvoiceMetadata(input.agreementId, input.instalmentNumber),
  };
}

/**
 * The invoice itself.
 *
 * ── collection_method "charge_automatically" ──────────────────
 *
 * The approved decision: Stripe collects from the customer's stored
 * payment method and Stripe DUNNING owns the retries. Package 5B took
 * the mandate for exactly this, with
 * payment_intent_data.setup_future_usage "off_session" on the first
 * instalment's Checkout Session, which attaches the PaymentMethod to the
 * Customer and records the customer's consent while they were present.
 *
 * ── auto_advance false HERE, true AT FINALIZE ─────────────────
 *
 * Created as a draft so the invoice id exists and can be recorded before
 * anything is charged, then finalized with auto_advance true so Stripe
 * takes over collection and retries. Creating it already-advancing would
 * mean the charge could succeed before this system knew the invoice
 * existed.
 *
 * pending_invoice_items_behavior "exclude" so the invoice picks up ONLY
 * the item created for it - never some other pending item that happens
 * to sit on the same customer.
 */
export function buildB2bInstalmentInvoiceParams(
  input: B2bInstalmentInvoiceInput
): Stripe.InvoiceCreateParams {
  return {
    customer: input.stripeCustomerId,
    currency: input.currency.toLowerCase(),
    collection_method: "charge_automatically",
    auto_advance: false,
    pending_invoice_items_behavior: "exclude",
    description:
      `GLOA Matcha B2B – Jahresvertrag, Rate ${input.instalmentNumber} von ${input.instalmentCount}`,
    metadata: b2bInvoiceMetadata(input.agreementId, input.instalmentNumber),
  };
}

/**
 * Correlation identifiers only. No amount, no company name, no email:
 * everything the webhook needs it re-reads from the database against
 * these two ids.
 */
export function b2bInvoiceMetadata(
  agreementId: string,
  instalmentNumber: number
): Record<string, string> {
  return {
    [B2B_INVOICE_AGREEMENT_METADATA_KEY]: agreementId,
    [B2B_INVOICE_INSTALMENT_METADATA_KEY]: String(instalmentNumber),
  };
}

/**
 * Does this finalized invoice match what the schedule says is owed?
 *
 * The frozen net is the authority. An invoice whose total is not the
 * derived gross is refused rather than settled - the same rule the
 * checkout settlement applies to a Checkout Session's amount_total.
 */
export function invoiceAmountMatches(
  invoice: { total?: number | null; currency?: string | null },
  charge: B2bInstalmentCharge,
  expectedCurrency: string
): boolean {
  if (typeof invoice.total !== "number") return false;
  if ((invoice.currency ?? "").toLowerCase() !== expectedCurrency.toLowerCase()) return false;
  return invoice.total === charge.grossCents;
}
