import type Stripe from "stripe";

/**
 * Every decision the annual later-instalment billing makes, and none of
 * the side effects (Package 5D).
 *
 * A LEAF: type-only imports, no relative value import, no database, no
 * network, no Stripe client, no clock. The flow lives in
 * lib/b2bRuntime.ts and its wiring in lib/b2bRuntimeDeps.ts.
 *
 * ── WHAT THIS FILE REFUSES TO DO ──────────────────────────────
 *
 * It computes no net amount and picks no due date. Migration 062 froze
 * the canonical allocation at activation and 063 owns the due rule; this
 * module turns one already-decided instalment into Stripe parameters,
 * and adds the VAT through the one tax authority.
 */

/* ── The routing key for an ANNUAL invoice ──────────────────── */

/**
 * THE KEY THAT MAKES AN ANNUAL INVOICE RECOGNISABLE.
 *
 * Restated here rather than imported from lib/b2bWebhookRules.ts,
 * exactly as that module restates the checkout key: a value import
 * between two sibling leaves would make both unloadable by the test
 * runner. The focused suite asserts the two agree.
 *
 * An annual instalment invoice is created by GLOA and carries this key
 * in its OWN metadata. A monthly invoice is generated by Stripe from a
 * subscription and carries no GLOA metadata at all - its agreement is
 * found through the SUBSCRIPTION's metadata instead. That difference is
 * what separates the two B2B invoice populations without either having
 * to know about the other.
 */
export const B2B_INVOICE_AGREEMENT_METADATA_KEY = "gloa_b2b_agreement_id";

/** Which instalment of the schedule this invoice collects. */
export const B2B_INVOICE_INSTALMENT_METADATA_KEY = "gloa_b2b_instalment_number";

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export type B2bAnnualInvoiceRouting =
  /** Not a GLOA-issued annual instalment invoice. */
  | { kind: "not_annual" }
  | { kind: "annual"; agreementId: string; instalmentNumber: number }
  /**
   * Annual by the routing key, but unusable. NOT "not annual": an
   * invoice carrying an agreement id IS an annual instalment, and
   * letting it fall through would settle a business contract through a
   * handler written for something else.
   */
  | { kind: "malformed"; reason: string };

/**
 * Decides whether a Stripe Invoice is a GLOA annual instalment.
 *
 * Reads the INVOICE's own metadata, which only this package ever writes.
 * A consumer subscription invoice, a B2B monthly invoice and a one-off
 * invoice all answer not_annual and keep their existing handlers.
 */
export function routeB2bAnnualInvoice(
  metadata: Stripe.Metadata | Record<string, unknown> | null | undefined
): B2bAnnualInvoiceRouting {
  const raw = (metadata ?? {}) as Record<string, unknown>;
  const agreementId = raw[B2B_INVOICE_AGREEMENT_METADATA_KEY];

  if (typeof agreementId !== "string" || agreementId.trim() === "") {
    return { kind: "not_annual" };
  }
  if (!UUID_RE.test(agreementId)) {
    return { kind: "malformed", reason: `${B2B_INVOICE_AGREEMENT_METADATA_KEY} is not a uuid` };
  }

  const rawNumber = raw[B2B_INVOICE_INSTALMENT_METADATA_KEY];
  const instalmentNumber = typeof rawNumber === "string" ? Number(rawNumber) : rawNumber;
  if (typeof instalmentNumber !== "number"
    || !Number.isInteger(instalmentNumber)
    || instalmentNumber < 2
    || instalmentNumber > 4) {
    // 2..4: instalment 1 is settled at activation and never invoiced,
    // and the approved schedules are 1, 2 and 4.
    return { kind: "malformed", reason: `${B2B_INVOICE_INSTALMENT_METADATA_KEY} is not an invoiceable instalment` };
  }

  return { kind: "annual", agreementId, instalmentNumber };
}

/* ── Idempotency ────────────────────────────────────────────── */

/**
 * The Stripe idempotency keys for one instalment's invoice and its item.
 *
 * DETERMINISTIC, derived only from the agreement uuid and the instalment
 * number. This is the crash-safety half of Package 5D: if the server
 * creates the invoice and dies before recording it, the next cron run
 * sends the SAME key and Stripe replays the original response instead of
 * minting a second invoice. Migration 063's unique
 * b2b_payment_schedule_stripe_invoice_id_key is the other half.
 *
 * No email, no name, no amount - an idempotency key is echoed in
 * Stripe's logs and is not a place for personal data.
 */
export function b2bInstalmentInvoiceIdempotencyKey(
  agreementId: string,
  instalmentNumber: number
): string {
  return `gloa-b2b-invoice-${agreementId}-${instalmentNumber}`;
}

export function b2bInstalmentItemIdempotencyKey(
  agreementId: string,
  instalmentNumber: number
): string {
  return `gloa-b2b-invoice-item-${agreementId}-${instalmentNumber}`;
}

/* ── The Stripe parameters ──────────────────────────────────── */

export type B2bInstalmentCharge = {
  netCents: number;
  taxCents: number;
  grossCents: number;
  taxRatePercent: number;
};

export type B2bInstalmentInvoiceInput = {
  agreementId: string;
  instalmentNumber: number;
  instalmentCount: number;
  stripeCustomerId: string;
  currency: string;
  charge: B2bInstalmentCharge;
};

/**
 * The invoice item: one line, the instalment's GROSS.
 *
 * GROSS, because B2B pricing is net-origin and lib/tax.ts has already
 * produced the final figure. Stripe is not asked to compute any tax -
 * there is deliberately no automatic_tax and no tax_behavior anywhere in
 * this flow, because a second opinion about VAT is exactly the thing
 * migration 060 refuses to store.
 */
export function buildB2bInstalmentItemParams(
  input: B2bInstalmentInvoiceInput & { invoiceId: string }
): Stripe.InvoiceItemCreateParams {
  return {
    customer: input.stripeCustomerId,
    // ── BOUND TO ONE INVOICE, EXPLICITLY ────────────────────────
    //
    // THIS IS THE FIX. An InvoiceItem created WITHOUT an invoice id is a
    // PENDING item on the Customer, and the SDK is explicit about what
    // happens to it: "For standalone invoices, the invoice item won't be
    // automatically added unless you pass pending_invoice_item_behavior:
    // 'include' when creating the invoice" - and
    // pending_invoice_items_behavior "Defaults to exclude if the
    // parameter is omitted".
    //
    // So the original order - item first, then an invoice created with
    // 'exclude' - produced an EMPTY invoice. It would have finalized at
    // zero and collected nothing, while the database recorded the
    // instalment as invoiced.
    //
    // Binding the item to a named draft invoice fixes it and is strictly
    // safer than the 'include' alternative, because 'include' sweeps in
    // EVERY pending item the Customer happens to have - and this
    // Customer is shared with B2C, so an unrelated pending item could
    // legitimately exist.
    invoice: input.invoiceId,
    currency: input.currency.toLowerCase(),
    amount: input.charge.grossCents,
    description:
      `GLOA Matcha B2B – Rate ${input.instalmentNumber} von ${input.instalmentCount}`,
    metadata: b2bInvoiceMetadata(input.agreementId, input.instalmentNumber),
  };
}

/**
 * The invoice itself.
 *
 * ── collection_method "charge_automatically" ──────────────────
 *
 * The approved decision: Stripe collects from the customer's stored
 * payment method and Stripe DUNNING owns the retries. Package 5B took
 * the mandate for exactly this, with
 * payment_intent_data.setup_future_usage "off_session" on the first
 * instalment's Checkout Session, which attaches the PaymentMethod to the
 * Customer and records the customer's consent while they were present.
 *
 * ── auto_advance false HERE, true AT FINALIZE ─────────────────
 *
 * Created as a draft so the invoice id exists and can be recorded before
 * anything is charged, then finalized with auto_advance true so Stripe
 * takes over collection and retries. Creating it already-advancing would
 * mean the charge could succeed before this system knew the invoice
 * existed.
 *
 * pending_invoice_items_behavior "exclude" so the invoice picks up ONLY
 * the item created for it - never some other pending item that happens
 * to sit on the same customer.
 */
export function buildB2bInstalmentInvoiceParams(
  input: B2bInstalmentInvoiceInput & { defaultPaymentMethodId: string }
): Stripe.InvoiceCreateParams {
  return {
    customer: input.stripeCustomerId,
    currency: input.currency.toLowerCase(),
    collection_method: "charge_automatically",
    auto_advance: false,
    // ── THE PAYMENT METHOD IS NAMED, NOT LEFT TO STRIPE ─────────
    //
    // THIS IS THE SECOND FIX. setup_future_usage "off_session" on
    // instalment 1 makes the PaymentMethod reusable and attaches it to
    // the Customer. It does NOT set
    // customer.invoice_settings.default_payment_method, and the SDK says
    // an invoice without default_payment_method "defaults to the
    // subscription's default payment method, if any, or to the default
    // payment method in the customer's invoice settings" - neither of
    // which this flow has established. Collection would then depend on
    // whatever Stripe happened to find.
    //
    // So the PaymentMethod that paid instalment 1 is named HERE, on the
    // invoice, and deliberately NOT on the Customer: public
    // stripe_customers is keyed on user_id, so ONE Stripe Customer
    // serves every GLOA product that user buys. Writing
    // customer.invoice_settings.default_payment_method would change
    // which card a B2C four-weekly subscription renews on, which is not
    // this package's decision to make.
    default_payment_method: input.defaultPaymentMethodId,
    // pending_invoice_items_behavior is deliberately ABSENT. It defaults
    // to 'exclude', which is what this invoice wants: its one line is
    // bound to it explicitly by invoice id, so no pending item - B2B or
    // B2C - can drift onto it.
    description:
      `GLOA Matcha B2B – Jahresvertrag, Rate ${input.instalmentNumber} von ${input.instalmentCount}`,
    metadata: b2bInvoiceMetadata(input.agreementId, input.instalmentNumber),
  };
}

/**
 * Correlation identifiers only. No amount, no company name, no email:
 * everything the webhook needs it re-reads from the database against
 * these two ids.
 */
export function b2bInvoiceMetadata(
  agreementId: string,
  instalmentNumber: number
): Record<string, string> {
  return {
    [B2B_INVOICE_AGREEMENT_METADATA_KEY]: agreementId,
    [B2B_INVOICE_INSTALMENT_METADATA_KEY]: String(instalmentNumber),
  };
}

/**
 * Does this finalized invoice match what the schedule says is owed?
 *
 * The frozen net is the authority. An invoice whose total is not the
 * derived gross is refused rather than settled - the same rule the
 * checkout settlement applies to a Checkout Session's amount_total.
 */
export function invoiceAmountMatches(
  invoice: { total?: number | null; currency?: string | null },
  charge: B2bInstalmentCharge,
  expectedCurrency: string
): boolean {
  if (typeof invoice.total !== "number") return false;
  if ((invoice.currency ?? "").toLowerCase() !== expectedCurrency.toLowerCase()) return false;
  return invoice.total === charge.grossCents;
}

/* ── Proving the draft is what it should be ─────────────────── */

/** One line of a draft invoice, as much of it as this check needs. */
export type B2bInvoiceLine = {
  amount?: number | null;
  currency?: string | null;
  metadata?: Record<string, string> | null;
  description?: string | null;
};

export type B2bDraftVerdict =
  | { ok: true }
  | { ok: false; reason: string };

/**
 * Does this draft invoice hold EXACTLY the intended instalment line?
 *
 * The check a mocked call order cannot make, and the reason it exists:
 * the original flow created a pending item and an invoice that excluded
 * it, so the draft was empty. An emptiness that a stubbed
 * `createInvoiceItem` returning `{id}` happily reports as success.
 *
 * So the draft is READ BACK before it is finalized, and finalization is
 * refused unless it carries one line, for the exact gross, in the
 * expected currency, carrying this instalment's own metadata. A second
 * line - an unrelated pending item that drifted in, a duplicate of this
 * one - is a refusal, not a rounding error: finalizing it would charge
 * the business for something nobody priced.
 */
export function verifyB2bInstalmentDraft(
  invoice: { status?: string | null; total?: number | null; currency?: string | null;
             lines?: { data?: B2bInvoiceLine[] } | null },
  input: { agreementId: string; instalmentNumber: number; currency: string;
           charge: B2bInstalmentCharge }
): B2bDraftVerdict {
  if (invoice.status !== "draft") {
    return { ok: false, reason: `invoice is ${invoice.status ?? "unknown"}, not draft` };
  }

  const lines = invoice.lines?.data ?? [];
  if (lines.length !== 1) {
    return { ok: false, reason: `draft holds ${lines.length} line(s), expected exactly 1` };
  }

  const line = lines[0];
  if (line.amount !== input.charge.grossCents) {
    return { ok: false, reason: `line is ${line.amount} cents, expected ${input.charge.grossCents}` };
  }
  if ((line.currency ?? "").toLowerCase() !== input.currency.toLowerCase()) {
    return { ok: false, reason: `line is in ${line.currency}, expected ${input.currency}` };
  }

  const meta = line.metadata ?? {};
  if (meta[B2B_INVOICE_AGREEMENT_METADATA_KEY] !== input.agreementId) {
    return { ok: false, reason: "line does not carry this agreement's id" };
  }
  if (meta[B2B_INVOICE_INSTALMENT_METADATA_KEY] !== String(input.instalmentNumber)) {
    return { ok: false, reason: "line does not carry this instalment number" };
  }

  // The invoice total must be the line, and nothing else.
  if (typeof invoice.total === "number" && invoice.total !== input.charge.grossCents) {
    return { ok: false, reason: `draft total is ${invoice.total}, expected ${input.charge.grossCents}` };
  }

  return { ok: true };
}

/**
 * The PaymentMethod that settled instalment 1, proved to belong to the
 * same Stripe Customer.
 *
 * Read from the authoritative PaymentIntent rather than assumed: 060
 * stored that intent's id on instalment 1's payment row at activation,
 * so the chain is row -> PaymentIntent -> PaymentMethod, with the
 * Customer checked at the last step.
 *
 * A PaymentMethod on a different Customer is REFUSED. Stripe would
 * refuse it too - "It must belong to the customer associated with the
 * invoice" - but failing here means the invoice is never created rather
 * than created and then rejected.
 */
export function resolveInstalmentPaymentMethod(
  paymentIntent: { customer?: unknown; payment_method?: unknown },
  expectedCustomerId: string
): { ok: true; paymentMethodId: string } | { ok: false; reason: string } {
  const idOf = (value: unknown): string | null => {
    if (typeof value === "string") return value.trim() || null;
    if (value && typeof value === "object" && typeof (value as { id?: unknown }).id === "string") {
      return (value as { id: string }).id;
    }
    return null;
  };

  const paymentMethodId = idOf(paymentIntent.payment_method);
  if (!paymentMethodId) {
    return { ok: false, reason: "the first instalment's PaymentIntent carries no payment method" };
  }
  const customerId = idOf(paymentIntent.customer);
  if (!customerId) {
    return { ok: false, reason: "the first instalment's PaymentIntent carries no customer" };
  }
  if (customerId !== expectedCustomerId) {
    return {
      ok: false,
      reason: "the first instalment's PaymentIntent belongs to a different Stripe customer",
    };
  }
  return { ok: true, paymentMethodId };
}

/* ══════════════════════════════════════════════════════════════
   ORPHAN DRAFT RECOVERY
   ══════════════════════════════════════════════════════════════

   ── WHY A DETERMINISTIC IDEMPOTENCY KEY IS NOT ENOUGH ─────────

   Stripe documents that an idempotency key may be pruned once it is at
   least 24 hours old, and a request replayed with a pruned key EXECUTES
   AGAIN. So this sequence is not durably convergent on its own:

     invoices.create succeeds -> the process dies before the database
     correlation -> the row is still 'scheduled' -> the cron does not run
     for more than a day -> the key is pruned -> the retry creates a
     SECOND draft for the same instalment.

   Neither draft would auto-charge, because both are created with
   auto_advance false. But two billing objects for one instalment is not
   an acceptable resting state: somebody could finalize the wrong one by
   hand, and the reconciliation pass would then find an invoice the
   database has never heard of.

   ── SO THE RECOVERY IDENTITY IS THE METADATA ──────────────────

   The agreement id and the instalment number are already on every
   invoice this package issues, and together they are unique: one
   instalment of one agreement. That pair is a DURABLE identity with no
   expiry, so an orphan draft can be found and ADOPTED rather than
   duplicated.

   It is used ONLY for this narrow pre-correlation window. The database
   row stays the canonical internal state; once
   b2b_payment_schedule.stripe_invoice_id is set, recovery goes through
   b2b_annual_instalments_unfinalized instead and never lists anything.

   ── AND NOT THROUGH STRIPE SEARCH ─────────────────────────────

   Search is eventually consistent, which is precisely wrong for a
   read-after-write recovery: the draft this code just created may not be
   indexed yet. invoices.list for one Customer is strongly consistent, so
   the filtering happens here instead. */

/** The two metadata fields that identify one instalment's invoice. */
export type B2bInstalmentIdentity = {
  agreementId: string;
  instalmentNumber: number;
};

/**
 * Is this invoice THE invoice for this instalment?
 *
 * Both keys, exactly. The agreement id alone would match every
 * instalment of the same contract, and the instalment number alone would
 * match every contract's second instalment.
 */
export function matchesB2bInstalmentIdentity(
  invoice: { metadata?: Record<string, string> | null },
  identity: B2bInstalmentIdentity
): boolean {
  const meta = invoice.metadata ?? {};
  return meta[B2B_INVOICE_AGREEMENT_METADATA_KEY] === identity.agreementId
    && meta[B2B_INVOICE_INSTALMENT_METADATA_KEY] === String(identity.instalmentNumber);
}

export type B2bAdoptionVerdict =
  /** Adoptable and already carrying its one canonical line. */
  | { ok: true; needsLine: false }
  /** Adoptable but empty - the caller adds the one line to THIS invoice. */
  | { ok: true; needsLine: true }
  | { ok: false; reason: string };

/**
 * May this orphan draft be adopted, and does it still need its line?
 *
 * Every field that decides what the customer is charged is checked, and
 * ANY other shape is refused rather than repaired. Nothing here deletes
 * or rewrites a Stripe object: an invoice that is not exactly right is
 * left alone for a person to look at, and the instalment stays
 * uninvoiced, which is visible and safe.
 *
 * The two allowed shapes are the two a crash can actually leave behind:
 *
 *   0 lines   the process died between invoices.create and
 *             invoiceItems.create
 *   1 line    it died after the item but before the correlation
 *
 * Two lines, a wrong amount, a wrong currency, an unrelated line, a
 * foreign customer or a different PaymentMethod are all refusals.
 */
export function verifyB2bAdoptedDraft(
  invoice: {
    customer?: unknown;
    status?: string | null;
    currency?: string | null;
    collection_method?: string | null;
    default_payment_method?: unknown;
    metadata?: Record<string, string> | null;
    lines?: { data?: B2bInvoiceLine[] } | null;
  },
  input: {
    agreementId: string;
    instalmentNumber: number;
    stripeCustomerId: string;
    currency: string;
    charge: B2bInstalmentCharge;
    defaultPaymentMethodId: string;
  }
): B2bAdoptionVerdict {
  const idOf = (value: unknown): string | null => {
    if (typeof value === "string") return value.trim() || null;
    if (value && typeof value === "object" && typeof (value as { id?: unknown }).id === "string") {
      return (value as { id: string }).id;
    }
    return null;
  };

  // ── IDENTITY ────────────────────────────────────────────────
  if (idOf(invoice.customer) !== input.stripeCustomerId) {
    return { ok: false, reason: "draft belongs to a different Stripe customer" };
  }
  if (invoice.status !== "draft") {
    return { ok: false, reason: `draft is ${invoice.status ?? "unknown"}, not draft` };
  }
  if ((invoice.currency ?? "").toLowerCase() !== input.currency.toLowerCase()) {
    return { ok: false, reason: `draft is in ${invoice.currency}, expected ${input.currency}` };
  }
  if (invoice.collection_method !== "charge_automatically") {
    return { ok: false, reason: `draft collects by ${invoice.collection_method}` };
  }
  if (!matchesB2bInstalmentIdentity(invoice, input)) {
    return { ok: false, reason: "draft metadata is not this instalment's" };
  }
  if (idOf(invoice.default_payment_method) !== input.defaultPaymentMethodId) {
    // A draft naming another card would collect from the wrong place.
    return { ok: false, reason: "draft names a different payment method" };
  }

  // ── LINES ───────────────────────────────────────────────────
  const lines = invoice.lines?.data ?? [];
  if (lines.length === 0) return { ok: true, needsLine: true };
  if (lines.length > 1) {
    return { ok: false, reason: `draft holds ${lines.length} lines, expected 0 or 1` };
  }

  const line = lines[0];
  if (line.amount !== input.charge.grossCents) {
    return { ok: false, reason: `draft line is ${line.amount} cents, expected ${input.charge.grossCents}` };
  }
  if ((line.currency ?? "").toLowerCase() !== input.currency.toLowerCase()) {
    return { ok: false, reason: `draft line is in ${line.currency}` };
  }
  if (!matchesB2bInstalmentIdentity({ metadata: line.metadata ?? null }, input)) {
    return { ok: false, reason: "draft line metadata is not this instalment's" };
  }

  return { ok: true, needsLine: false };
}
