-- ============================================================
-- GLOA – Customer Order Lifecycle: shipping/tracking, refund state,
-- cancellation requests (Task 26A)
-- Run in Supabase SQL Editor AFTER 018
--
-- 019 is the genuinely next free migration number: 017 is the order
-- confirmation email state (Task 24A), 018 is customer withdrawal
-- requests (Task 25A). Neither is touched here. Task 21 (tax/VAT/OSS)
-- has still never created a migration file and remains free to take a
-- later number - this migration deliberately writes no tax field and
-- leaves every existing *_net_cents / tax_total_cents column exactly as
-- it is, NULL included.
--
-- Everything here is additive. No existing column, constraint value,
-- policy, or grant is removed, and no historical order is rewritten:
-- every new column is nullable with no default, so orders that predate
-- this migration read as "unknown", never as a fabricated state. In
-- particular refunded_total_cents stays NULL rather than 0 for old
-- orders - "we have never looked" and "we looked and it was zero" are
-- different facts, and the customer UI renders them differently.
--
-- Tracking data is populated externally (the owner enters it), not by
-- any carrier API - so service_role deliberately gets NO write access to
-- the tracking columns. The website only ever reads them.
-- ============================================================

-- 1. TRACKING / SHIPPING COLUMNS ───────────────────────────────
--
-- Carrier is free text and may legitimately stay NULL: we never guess a
-- carrier from the shape of a tracking number. tracking_url is likewise
-- never synthesised from a carrier name - if the owner has no real URL,
-- the customer sees the bare tracking number instead of a fabricated
-- DHL/UPS/DPD link.
alter table public.orders
  add column if not exists shipping_carrier text,
  add column if not exists tracking_number  text,
  add column if not exists tracking_url     text,
  add column if not exists shipped_at       timestamptz;

-- Defense in depth against a stored javascript:/data: URL ever reaching
-- an anchor href. The customer UI validates the scheme again at render
-- time (lib/orderStatus.ts), but a bad row should not exist in the first
-- place. Blank strings are rejected too, so "no tracking" is expressed
-- one way only: NULL.
alter table public.orders
  drop constraint if exists orders_tracking_url_scheme_check,
  drop constraint if exists orders_tracking_number_not_blank_check,
  drop constraint if exists orders_shipping_carrier_not_blank_check;

alter table public.orders
  add constraint orders_tracking_url_scheme_check
    check (tracking_url is null or tracking_url ~* '^https?://[^[:space:]]+$'),
  add constraint orders_tracking_number_not_blank_check
    check (tracking_number is null or btrim(tracking_number) <> ''),
  add constraint orders_shipping_carrier_not_blank_check
    check (shipping_carrier is null or btrim(shipping_carrier) <> '');

-- 2. REFUND STATE ──────────────────────────────────────────────
--
-- An actual refunded amount in cents, never a boolean: a partial refund
-- is a first-class case and "refund = order total" must never be
-- assumed. NULL means no refund has ever been observed for this order.
-- The amount can never exceed what the order was actually charged.
alter table public.orders
  add column if not exists refunded_total_cents integer,
  add column if not exists refund_updated_at    timestamptz;

alter table public.orders
  drop constraint if exists orders_refunded_total_cents_range_check;

alter table public.orders
  add constraint orders_refunded_total_cents_range_check
    check (
      refunded_total_cents is null
      or (refunded_total_cents >= 0 and refunded_total_cents <= total_gross_cents)
    );

-- 'refund_pending' is added to the existing payment_status vocabulary
-- because Stripe genuinely reports it: a Refund object carries
-- status='pending' before it settles. It is not an invented operational
-- state. Every previously allowed value is preserved, so no existing row
-- can violate the replacement constraint.
-- The existing constraint's name is auto-generated by Postgres and is
-- not assumed here: every CHECK on public.orders that actually mentions
-- payment_status is dropped by definition, so a differently-named
-- constraint cannot survive and silently keep rejecting the new value.
do $$
declare
  v_constraint record;
begin
  for v_constraint in
    select conname
    from pg_constraint
    where conrelid = 'public.orders'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%payment_status%'
  loop
    execute format('alter table public.orders drop constraint %I', v_constraint.conname);
  end loop;
end
$$;

alter table public.orders
  add constraint orders_payment_status_check
    check (payment_status in (
      'pending', 'paid', 'failed',
      'refund_pending', 'partially_refunded', 'refunded'
    ));

-- 3. CANCELLATION REQUEST ──────────────────────────────────────
--
-- This records that a customer ASKED whether an order can still be
-- stopped. It is explicitly not a cancellation: only the owner can
-- actually cancel, by setting status/fulfillment_status. The customer UI
-- says "Wir prüfen, ob die Bestellung noch gestoppt werden kann.", never
-- "Bestellung storniert".
--
-- This is also completely separate from the § 356a legal withdrawal
-- declaration in public.withdrawal_requests (migration 018), which is
-- untouched by this migration. A cancellation request is an operational
-- courtesy; a withdrawal is a statutory declaration. They must not be
-- conflated, and neither implies the other.
alter table public.orders
  add column if not exists cancellation_requested_at timestamptz,
  add column if not exists cancellation_request_note text;

alter table public.orders
  drop constraint if exists orders_cancellation_request_note_length_check;

alter table public.orders
  add constraint orders_cancellation_request_note_length_check
    check (cancellation_request_note is null or char_length(cancellation_request_note) <= 2000);

-- 4. CANCELLATION REQUEST FUNCTION ─────────────────────────────
--
-- SECURITY DEFINER, matching the create_order_from_paid_checkout pattern
-- from migration 011: service_role keeps its read-only SELECT on
-- public.orders and never receives a blanket UPDATE grant. Every write
-- this feature can perform is confined to exactly the two cancellation
-- columns inside this function body.
--
-- Ownership is enforced here, in the database, against the user id the
-- API route already verified against Supabase Auth - not against
-- anything the browser claimed. A row that does not belong to the caller
-- is indistinguishable from a row that does not exist ('not_found' in
-- both cases), so this cannot be used to probe which order ids are real.
--
-- Returns a status string rather than raising, so ordinary outcomes stay
-- ordinary control flow:
--   'not_found'         - no such order, or not this user's order
--   'not_eligible'      - already cancelled/refunded, or already shipped
--   'already_requested' - idempotent repeat, nothing changed
--   'requested'         - recorded now
create or replace function public.request_order_cancellation(
  p_order_id uuid,
  p_user_id  uuid,
  p_note     text
)
returns text
language plpgsql
volatile
security definer set search_path = ''
as $$
declare
  v_order public.orders;
begin
  if p_order_id is null or p_user_id is null then
    return 'not_found';
  end if;

  select * into v_order
  from public.orders
  where id = p_order_id
    and user_id = p_user_id
  for update;

  if not found then
    return 'not_found';
  end if;

  -- Idempotent: a second submission is not an error and must not move
  -- the timestamp, which would misrepresent when the customer asked.
  if v_order.cancellation_requested_at is not null then
    return 'already_requested';
  end if;

  -- State transition validated server-side. Once something has shipped,
  -- fulfillment cannot be un-done and the honest answer is the statutory
  -- withdrawal route, not a cancellation request.
  if v_order.status in ('cancelled', 'refunded', 'shipped', 'delivered')
     or v_order.fulfillment_status in ('cancelled', 'shipped', 'delivered')
     or v_order.payment_status in ('refunded', 'partially_refunded')
  then
    return 'not_eligible';
  end if;

  update public.orders
     set cancellation_requested_at = now(),
         cancellation_request_note = nullif(btrim(coalesce(p_note, '')), '')
   where id = p_order_id;

  return 'requested';
end;
$$;

revoke all on function public.request_order_cancellation(uuid, uuid, text) from public;
grant execute on function public.request_order_cancellation(uuid, uuid, text) to service_role;

-- 5. REFUND STATE FUNCTION ─────────────────────────────────────
--
-- Applies an ABSOLUTE refunded total that the caller has already read
-- back from Stripe (lib/orderRefunds.ts re-lists the refunds for the
-- payment intent rather than trusting the webhook payload). Absolute,
-- not incremental, is what makes this safe under duplicate, retried, and
-- out-of-order webhook deliveries: applying the same event twice yields
-- the same row, and a stale delivery cannot double-count.
--
-- Deliberately narrow:
--   * matches on stripe_payment_intent_id only, so it cannot touch an
--     unrelated order. There is no unique index on that column, so an
--     ambiguous match is refused outright rather than guessed at.
--   * refuses an amount above what the order was actually charged.
--   * never writes status, fulfillment_status, or any money column. A
--     refund is a payment fact; whether the order is operationally
--     "cancelled" stays the owner's decision.
--   * leaves an unpaid order alone entirely.
--
-- Returns:
--   'invalid_input' / 'order_not_found' / 'ambiguous_payment_intent'
--   'invalid_amount' / 'not_applicable' / 'unchanged' / 'applied'
create or replace function public.apply_order_refund_state(
  p_payment_intent_id   text,
  p_refunded_total_cents integer,
  p_has_pending_refund  boolean
)
returns text
language plpgsql
volatile
security definer set search_path = ''
as $$
declare
  v_order       public.orders;
  v_match_count integer;
  v_new_status  text;
begin
  if p_payment_intent_id is null
     or btrim(p_payment_intent_id) = ''
     or p_refunded_total_cents is null
     or p_refunded_total_cents < 0
  then
    return 'invalid_input';
  end if;

  select count(*) into v_match_count
  from public.orders
  where stripe_payment_intent_id = p_payment_intent_id;

  if v_match_count = 0 then
    return 'order_not_found';
  end if;

  -- Never guess which order a refund belongs to.
  if v_match_count > 1 then
    return 'ambiguous_payment_intent';
  end if;

  select * into v_order
  from public.orders
  where stripe_payment_intent_id = p_payment_intent_id
  for update;

  -- An order that was never paid has no refund story to tell.
  if v_order.payment_status not in ('paid', 'refund_pending', 'partially_refunded', 'refunded') then
    return 'not_applicable';
  end if;

  if p_refunded_total_cents > v_order.total_gross_cents then
    return 'invalid_amount';
  end if;

  if p_refunded_total_cents >= v_order.total_gross_cents and v_order.total_gross_cents > 0 then
    v_new_status := 'refunded';
  elsif p_refunded_total_cents > 0 then
    v_new_status := 'partially_refunded';
  elsif coalesce(p_has_pending_refund, false) then
    v_new_status := 'refund_pending';
  else
    -- No settled and no pending refund: any earlier refund attempt was
    -- cancelled or failed, so the order is simply paid again.
    v_new_status := 'paid';
  end if;

  if v_order.payment_status = v_new_status
     and v_order.refunded_total_cents is not distinct from p_refunded_total_cents
  then
    return 'unchanged';
  end if;

  update public.orders
     set payment_status       = v_new_status,
         refunded_total_cents = p_refunded_total_cents,
         refund_updated_at    = now()
   where id = v_order.id;

  return 'applied';
end;
$$;

revoke all on function public.apply_order_refund_state(text, integer, boolean) from public;
grant execute on function public.apply_order_refund_state(text, integer, boolean) to service_role;

-- 6. NO NEW CLIENT PRIVILEGES ──────────────────────────────────
--
-- The new columns are readable by the customer through the SELECT grant
-- and "Users read own orders" RLS policy that migration 004 already
-- established - a customer can read tracking and refund state on their
-- own order and nothing else. No INSERT/UPDATE/DELETE policy or grant is
-- added for anon or authenticated by this migration, and anon still has
-- no access to public.orders at all.

-- 7. HOW TRACKING GETS POPULATED ───────────────────────────────
--
-- There is no carrier integration. When an order actually ships, the
-- owner sets the tracking fields (and the fulfillment status) directly,
-- e.g.:
--
--   update public.orders
--      set fulfillment_status = 'shipped',
--          shipped_at         = now(),
--          shipping_carrier   = 'DHL',          -- or NULL if unknown
--          tracking_number    = '00340434161094042557',
--          tracking_url       = 'https://...'   -- or NULL if there is none
--    where order_number = 'GLOA-2026-000123';
--
-- Leave any field NULL rather than filling it with a guess: the customer
-- UI renders a bare tracking number perfectly well without a carrier,
-- and shows no link at all rather than a fabricated one.
--
-- 'delivered' is deliberately never set automatically anywhere in this
-- codebase. Set fulfillment_status = 'delivered' only if there is a real
-- delivery confirmation; otherwise 'shipped' remains the honest state.
